import puppeteer from 'puppeteer';
const b=await puppeteer.launch({headless:'new',executablePath:'/opt/meta-chromium/chrome',args:['--no-sandbox','--allow-file-access-from-files','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader']});
const p=await b.newPage(); await p.setViewport({width:1280,height:800});
const errs=[]; p.on('pageerror',e=>errs.push('PAGEERROR '+e.message)); p.on('console',m=>{if(m.type()==='error')errs.push('CONSOLE '+m.text().slice(0,140))});
await p.goto('file:///home/hatch/workspace/your_files/washer-twin/wtw8540bw0-digital-twin.html',{waitUntil:'networkidle0',timeout:60000});
await p.waitForFunction('window.__twin && !document.getElementById("loader").offsetParent',{timeout:30000}).catch(()=>{});
await new Promise(r=>setTimeout(r,2000));
const rep=await p.evaluate(()=>{const t=window.__twin;
  document.querySelector('[data-tab="build"]').click();
  t.setAsmStep(6);
  let n=0; t.ASM.forEach(P=>P.g.traverse(o=>{if(o.isMesh)n++;}));
  return {nparts:t.ASM.length, meshes:n, cur:t.ASM[6].id};
});
console.log(JSON.stringify(rep));
const d=await p.evaluate(()=>{const t=window.__twin;t.renderer.render(t.scene,t.camera);return t.renderer.domElement.toDataURL('image/png')});
const{writeFileSync}=await import('fs');writeFileSync('/tmp/f1-plib.png',Buffer.from(d.split(',')[1],'base64'));
console.log('errors:',errs.length?errs.slice(0,6):'none');
await b.close();
