import puppeteer from 'puppeteer';
const b=await puppeteer.launch({headless:'new',executablePath:'/opt/meta-chromium/chrome',args:['--no-sandbox','--allow-file-access-from-files','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader']});
const p=await b.newPage(); await p.setViewport({width:1280,height:800});
await p.goto('file:///home/hatch/workspace/your_files/washer-twin/wtw8540bw0-digital-twin.html',{waitUntil:'networkidle0',timeout:60000});
await p.waitForFunction('window.__twin && !document.getElementById("loader").offsetParent',{timeout:30000}).catch(()=>{});
await new Promise(r=>setTimeout(r,2000));
await p.evaluate(()=>{document.querySelector('[data-tab="bearing"]').click()});
await new Promise(r=>setTimeout(r,1000));
await p.evaluate(()=>{document.querySelector('[data-bs="7"]').click()});
await new Promise(r=>setTimeout(r,1000));
await p.screenshot({path:'/tmp/b4-panel.png'});
console.log('panel html check:', await p.evaluate(()=>document.getElementById('panel').textContent.slice(0,80)));
await b.close();
