/**
 * Wave 8 — gtfs.de German realtime transit status (catalog Wave D item 68, #163).
 *
 * WHY A SNAPSHOT PIPELINE: https://realtime.gtfs.de/realtime-free.pb is a
 * GTFS-RT protobuf feed (~9–14 MB, regenerated ~every 10 s) carrying
 * TripUpdates + Alerts only (NO VehiclePositions). Pulling 10+ MB through
 * the edge on every cache miss is infeasible, and protobuf decode at the
 * edge is disallowed (same call as wave7/mbta.js: no WASM, no node:, and no
 * hand-rolled wire decoder in the Pages bundle). `scripts/gtfs-de-snapshot.mjs`
 * (the only place the .pb is ever downloaded — it runs in GitHub Actions
 * with node: and the repo's `pbf` decoder) decodes the feed, extracts the
 * most-delayed trips and the active service alerts, validates the result,
 * and publishes `gtfs-de-latest.json` to the `gtfs-de-latest` GitHub release
 * on Sheldondouthat/satwq-reality-os. THIS provider only ever fetches that
 * compact pre-computed snapshot — it never touches the protobuf.
 *
 * Routes:
 *   GET /api/gtfs-de → { generatedAt, stale, snapshot:{…}, counts, topDelayed, alerts, attribution }
 *
 * Keyless, gtfs.de data under CC BY-SA 4.0 (attribution carried in the
 * payload), Pages-safe (global fetch only, capped reads, redirect:'follow' —
 * workerd supports only 'follow'/'manual'; 'error' throws at the edge
 * (main 2ec4053), no node: imports, no WASM).
 *
 * Probe notes (2026-09-27, build VM): HEAD → 200, Apache, Last-Modified
 * refreshing every ~10 s. Full download is flaky mid-regeneration (curl
 * exit 18 — declared length vs regenerated bytes), so the snapshot script
 * retries. Decoded with pbf: FeedMessage → header.timestamp + entities;
 * entity 3 = trip_update {trip{trip_id, start_date}, delay,
 * stop_time_update[]{stop_id, arrival{delay}, departure{delay}}},
 * entity 5 = alert {header_text, description_text, cause, effect,
 * informed_entity[]{route_id, agency_id}}. Verified live 2026-09-27
 * 21:48:53 UTC: 31,738 entities → 13,488 trip updates + 18,250 alerts,
 * zero vehicle positions (TripDescriptor carries no route_id on most
 * entities; negative int32 delays decode, e.g. -12 s). The snapshot
 * release did not exist before this build — scripts/gtfs-de-snapshot.mjs
 * publishes it.
 */

import { readResponseTextCapped } from '../common/http.js';

const SNAPSHOT_URL =
  'https://github.com/Sheldondouthat/satwq-reality-os/releases/download/gtfs-de-latest/gtfs-de-latest.json';
const UPSTREAM_TIMEOUT_MS = 25_000;
const BODY_CAP_BYTES = 512 * 1024; // snapshots are <300 KB; 512 KB is generous headroom
const CACHE_TTL_MS = 15 * 60_000; // snapshot pipeline refreshes on a ~15 min cadence
const STALE_MS = 2 * 3600_000;
const RETRY_COOLDOWN_MS = 60_000;
const USER_AGENT = 'Gods Eye View (gtfs.de transit status layer)';
const SNAPSHOT_FORMAT = 'gtfs-de-snapshot';
// Generous sanity bounds: a delay beyond ±24 h is a corrupt feed, not a late train.
const MAX_ABS_DELAY_SEC = 24 * 3600;

/** GTFS-RT Alert.Cause enum → label. */
export const ALERT_CAUSES = Object.freeze({
  1: 'UNKNOWN_CAUSE',
  2: 'OTHER_CAUSE',
  3: 'TECHNICAL_PROBLEM',
  4: 'STRIKE',
  5: 'DEMONSTRATION',
  6: 'ACCIDENT',
  7: 'HOLIDAY',
  8: 'WEATHER',
  9: 'MAINTENANCE',
  10: 'CONSTRUCTION',
  11: 'POLICE_ACTIVITY',
  12: 'MEDICAL_EMERGENCY',
});

/** GTFS-RT Alert.Effect enum → label. */
export const ALERT_EFFECTS = Object.freeze({
  1: 'NO_SERVICE',
  2: 'REDUCED_SERVICE',
  3: 'SIGNIFICANT_DELAYS',
  4: 'DETOUR',
  5: 'ADDITIONAL_SERVICE',
  6: 'MODIFIED_SERVICE',
  7: 'OTHER_EFFECT',
  8: 'UNKNOWN_EFFECT',
  9: 'STOP_MOVED',
  10: 'NO_EFFECT',
  11: 'ACCESSIBILITY_ISSUE',
});

let cache = null; // {at, payload}
let inflight = null;
let attemptedAt = -Infinity;

function isValidDelay(d) {
  return Number.isFinite(d) && Math.abs(d) <= MAX_ABS_DELAY_SEC;
}

/** Worst (largest) delay across a trip update and all its stop-time updates. */
function tripDelayScore(tripUpdate) {
  const candidates = [tripUpdate?.delay];
  for (const stu of tripUpdate?.stopTimeUpdates ?? []) {
    candidates.push(stu?.arrivalDelay, stu?.departureDelay);
  }
  let worst = 0;
  for (const d of candidates) {
    if (isValidDelay(d) && d > worst) worst = d;
  }
  return worst;
}

/**
 * Assemble the publishable snapshot document from a decoded GTFS-RT feed.
 * Pure + deterministic; shared by scripts/gtfs-de-snapshot.mjs and the tests.
 *
 * `decoded` is the script-side decode output:
 *   { feedTimestamp, entities: [{ id, isDeleted, tripUpdate?, alert? }] }
 * where tripUpdate = { trip:{tripId, routeId, startDate}, delay,
 *   stopTimeUpdates:[{stopId, stopSequence, arrivalDelay, departureDelay}] }
 * and alert = { header, description, cause, effect, routes:[], agencyIds:[] }.
 */
export function buildGtfsDeSnapshot(
  decoded,
  { fetchedAt, topN = 100, maxAlerts = 50 } = {},
) {
  if (!decoded || typeof decoded !== 'object') {
    throw Object.assign(
      new Error('gtfs_de_snapshot_invalid: no decoded feed'),
      { status: 502 },
    );
  }
  if (
    typeof decoded.feedTimestamp !== 'string' ||
    !Number.isFinite(Date.parse(decoded.feedTimestamp))
  ) {
    throw Object.assign(
      new Error('gtfs_de_snapshot_invalid: bad feedTimestamp'),
      { status: 502 },
    );
  }
  const entities = Array.isArray(decoded.entities) ? decoded.entities : [];
  const counts = {
    entities: entities.length,
    tripUpdates: 0,
    alerts: 0,
    deleted: 0,
  };
  const delayed = [];
  const alerts = [];
  for (const e of entities) {
    if (e?.isDeleted) {
      counts.deleted++;
      continue;
    }
    if (e?.tripUpdate) {
      counts.tripUpdates++;
      const tu = e.tripUpdate;
      const worst = tripDelayScore(tu);
      let worstStopId = null;
      for (const stu of tu.stopTimeUpdates ?? []) {
        const d = Math.max(
          isValidDelay(stu?.arrivalDelay) ? stu.arrivalDelay : 0,
          isValidDelay(stu?.departureDelay) ? stu.departureDelay : 0,
        );
        if (d === worst && d > 0) {
          worstStopId = stu.stopId ?? null;
          break;
        }
      }
      if (worst > 0) {
        delayed.push({
          tripId: tu.trip?.tripId ?? null,
          routeId: tu.trip?.routeId ?? null,
          startDate: tu.trip?.startDate ?? null,
          delaySec: worst,
          stopUpdates: (tu.stopTimeUpdates ?? []).length,
          worstStopId,
        });
      }
    } else if (e?.alert) {
      counts.alerts++;
      const a = e.alert;
      alerts.push({
        id: e.id ?? null,
        header: a.header ?? '',
        description: a.description ?? '',
        cause: a.cause ?? null,
        causeLabel: ALERT_CAUSES[a.cause] ?? null,
        effect: a.effect ?? null,
        effectLabel: ALERT_EFFECTS[a.effect] ?? null,
        routes: a.routes ?? [],
        agencyIds: a.agencyIds ?? [],
      });
    }
  }
  delayed.sort((a, b) => b.delaySec - a.delaySec);
  const snap = {
    format: SNAPSHOT_FORMAT,
    formatVersion: 1,
    fetchedAt,
    feedTimestamp: decoded.feedTimestamp,
    counts,
    topDelayed: delayed.slice(0, topN),
    alerts: alerts.slice(0, maxAlerts),
  };
  validateGtfsDeSnapshot(snap);
  return snap;
}

/**
 * Validate a snapshot document (published asset or test fixture).
 * Throws gtfs_de_snapshot_invalid with status 502 — the asset is upstream
 * data, so a corrupt one is an upstream failure, not a code bug.
 */
export function validateGtfsDeSnapshot(snap) {
  const problems = [];
  if (snap?.format !== SNAPSHOT_FORMAT) problems.push('bad format marker');
  if (snap?.formatVersion !== 1) problems.push('unsupported formatVersion');
  if (
    typeof snap?.fetchedAt !== 'string' ||
    !Number.isFinite(Date.parse(snap.fetchedAt))
  ) {
    problems.push('bad fetchedAt');
  }
  if (
    typeof snap?.feedTimestamp !== 'string' ||
    !Number.isFinite(Date.parse(snap.feedTimestamp))
  ) {
    problems.push('bad feedTimestamp');
  }
  const counts = snap?.counts;
  if (
    !counts ||
    !Number.isInteger(counts.entities) ||
    !Number.isInteger(counts.tripUpdates) ||
    !Number.isInteger(counts.alerts) ||
    !Number.isInteger(counts.deleted) ||
    counts.entities < 0 ||
    counts.entities > 200000 ||
    counts.tripUpdates < 0 ||
    counts.alerts < 0 ||
    counts.deleted < 0 ||
    counts.tripUpdates + counts.alerts + counts.deleted > counts.entities
  ) {
    problems.push('bad counts');
  }
  const topDelayed = snap?.topDelayed;
  if (!Array.isArray(topDelayed)) {
    problems.push('topDelayed missing');
  } else {
    topDelayed.forEach((t, idx) => {
      if (!Number.isInteger(t?.delaySec) || !isValidDelay(t.delaySec) || t.delaySec <= 0) {
        problems.push(`topDelayed[${idx}]: bad delaySec`);
      }
      if (idx > 0 && topDelayed[idx - 1].delaySec < t.delaySec) {
        problems.push(`topDelayed[${idx}]: not sorted desc`);
      }
    });
  }
  const alerts = snap?.alerts;
  if (!Array.isArray(alerts)) {
    problems.push('alerts missing');
  } else {
    alerts.forEach((a, idx) => {
      if (typeof a?.header !== 'string')
        problems.push(`alerts[${idx}]: bad header`);
      if (a?.cause != null && !(a.cause in ALERT_CAUSES)) {
        problems.push(`alerts[${idx}]: unknown cause ${a.cause}`);
      }
      if (a?.effect != null && !(a.effect in ALERT_EFFECTS)) {
        problems.push(`alerts[${idx}]: unknown effect ${a.effect}`);
      }
    });
  }
  if (problems.length) {
    throw Object.assign(
      new Error(`gtfs_de_snapshot_invalid: ${problems.join('; ')}`),
      {
        status: 502,
      },
    );
  }
  return true;
}

async function fetchSnapshot(fetchImpl) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), UPSTREAM_TIMEOUT_MS);
  try {
    const res = await fetchImpl(SNAPSHOT_URL, {
      signal: controller.signal,
      // NOTE: redirect:'follow' — workerd supports only 'follow'/'manual';
      // 'error' throws at the edge (main 2ec4053). GitHub release assets
      // redirect to the CDN, so follow is required here.
      redirect: 'follow',
      headers: { 'User-Agent': USER_AGENT, Accept: 'application/json' },
    });
    if (!res.ok)
      throw Object.assign(new Error(`gtfs_de_snapshot_http_${res.status}`), {
        status: 502,
      });
    const text = await readResponseTextCapped(res, BODY_CAP_BYTES); // throws when too large
    const snap = JSON.parse(text);
    validateGtfsDeSnapshot(snap); // throws {status:502} on a corrupt asset — an upstream failure
    return snap;
  } finally {
    clearTimeout(timer);
  }
}

function buildPayload(snap, nowMs, stale) {
  return {
    generatedAt: new Date(nowMs).toISOString(),
    stale,
    snapshot: {
      format: snap.format,
      formatVersion: snap.formatVersion,
      fetchedAt: snap.fetchedAt,
      feedTimestamp: snap.feedTimestamp,
    },
    counts: snap.counts,
    topDelayed: snap.topDelayed,
    alerts: snap.alerts,
    attribution:
      'German realtime transit: gtfs.de realtime-free GTFS-RT (CC BY-SA 4.0). ' +
      'Snapshot: most-delayed trips + active alerts by scripts/gtfs-de-snapshot.mjs. ' +
      'This feed carries TripUpdates + Alerts only — no vehicle positions.',
  };
}

async function getPayload(fetchImpl, nowMs, signal) {
  // nowMs is the injected clock (tests control it); real Date.now() is never
  // used for cache age so staleness is deterministic under test.
  if (cache && nowMs - cache.at < CACHE_TTL_MS)
    return buildPayload(cache.payload, nowMs, false);
  signal?.throwIfAborted?.();
  if (!inflight) {
    if (nowMs - attemptedAt < RETRY_COOLDOWN_MS)
      throw new Error('gtfs_de_retry_later');
    attemptedAt = nowMs;
    inflight = fetchSnapshot(fetchImpl)
      .then((snap) => {
        cache = { at: nowMs, payload: snap };
        return buildPayload(snap, nowMs, false);
      })
      .finally(() => {
        inflight = null;
      });
  }
  if (!signal) return inflight;
  const cancelled = new Promise((_, reject) => {
    const abort = () => reject(signal.reason ?? new Error('cancelled'));
    signal.addEventListener('abort', abort, { once: true });
    const detach = () => signal.removeEventListener('abort', abort);
    inflight.then(detach, detach);
  });
  return Promise.race([inflight, cancelled]);
}

function sendJson(res, status, body, cacheControl = 'public, max-age=900') {
  res.writeHead(status, {
    'Content-Type': 'application/json; charset=utf-8',
    'Cache-Control': cacheControl,
  });
  res.end(JSON.stringify(body));
}

export function gtfsDeProxy({
  fetchImpl = fetch,
  now = () => Date.now(),
} = {}) {
  async function handler(req, res) {
    if (req.method !== 'GET')
      return sendJson(res, 405, { error: 'method_not_allowed' }, 'no-store');
    const controller = new AbortController();
    const close = () => controller.abort();
    res.once?.('close', close);
    try {
      try {
        sendJson(
          res,
          200,
          await getPayload(fetchImpl, now(), controller.signal),
        );
      } catch (error) {
        const usable = cache && now() - cache.at <= STALE_MS;
        if (usable) {
          sendJson(res, 200, buildPayload(cache.payload, now(), true));
          return;
        }
        const upstreamFail =
          error?.status === 502 ||
          error?.name === 'AbortError' ||
          /aborted?/i.test(error?.message ?? '');
        sendJson(
          res,
          upstreamFail ? 502 : 500,
          { error: 'gtfs_de_unavailable', detail: error?.message ?? 'unknown' },
          'no-store',
        );
      }
    } finally {
      res.removeListener?.('close', close);
    }
  }

  return {
    name: 'gtfs-de',
    configureServer({ middlewares }) {
      middlewares.use('/api/gtfs-de', handler);
    },
    configurePreviewServer({ middlewares }) {
      middlewares.use('/api/gtfs-de', handler);
    },
  };
}

export const _gtfsDeInternals = {
  SNAPSHOT_URL,
  ALERT_CAUSES,
  ALERT_EFFECTS,
  buildGtfsDeSnapshot,
  validateGtfsDeSnapshot,
  clearCaches: () => {
    cache = null;
    inflight = null;
    attemptedAt = -Infinity;
  },
};
