/**
 * Surge-500 spec test — AUTO-GENERATED by scripts/surge-generate.mjs.
 * Fixture: REAL upstream bytes captured live 2026-10-02
 * (surge-500 batch 7 (euro worker)). Do not edit by hand.
 */
import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import {
  validateSpec,
  extractItems,
  applyMap,
  filterRequired,
  buildPayload,
  specProxy,
  resolvePath,
} from '../../../server/providers/wave10/generic.js';
import { SPEC } from '../../../server/providers/wave10/specs/euro-paris-parking-garages.mjs';

const spec = SPEC;
const fixture = JSON.parse(readFileSync(
  new URL('../../../server/providers/wave10/fixtures/euro-paris-parking-garages.json', import.meta.url), 'utf8'));

test('spec validates against the schema', () => {
  assert.equal(validateSpec(spec), true);
  assert.match(spec.id, /^[a-z0-9][a-z0-9-]{0,47}$/);
  assert.equal(spec.id, 'euro-paris-parking-garages');
});

test('extract.items resolves ' + (false ? 'to an array (honest-empty allowed)' : 'to a non-empty array on the live fixture'), () => {
  const items = extractItems(spec, fixture);
  assert.ok(Array.isArray(items), 'items must be an array');
  assert.ok(items.length > 0, 'live probe returned zero items — must not ship');});

test('map resolves required fields ' + (false ? 'when rows exist' : 'on at least one row'), () => {
  const required = ["name","address"];
  const rows = extractItems(spec, fixture).map((item) => applyMap(spec, item));
  const { rows: kept } = filterRequired(spec, rows);
  assert.ok(kept.length > 0, `no row resolves required fields ${JSON.stringify(required)}`);
  for (const f of required) {
    assert.ok(kept.some((r) => r[f] != null && r[f] !== ''), `required field '${f}' null on every row`);
  }
});

test('numeric fields are null-or-finite (Number("")===0 trap guarded)', () => {
  const numbers = new Set(["total_spaces","disabled_spaces","bike_spaces","moto_spaces","carshare_spaces","max_height_cm","abo_resident","abo_non_resident","lon","lat"]);
  const rows = extractItems(spec, fixture).map((item) => applyMap(spec, item));
  for (const row of rows) {
    for (const f of numbers) {
      const v = row[f];
      assert.ok(v === null || (typeof v === 'number' && Number.isFinite(v)),
        `field '${f}' is not null-or-finite: ${JSON.stringify(v)}`);
    }
  }
});

test('payload envelope is well-formed', () => {
  const rows = filterRequired(spec,
    extractItems(spec, fixture).map((item) => applyMap(spec, item))).rows;
  const payload = buildPayload(spec, rows, false);
  assert.ok(payload.generatedAt);
  assert.equal(payload.id, 'euro-paris-parking-garages');
  assert.equal(payload.count, rows.length);
  assert.ok(Array.isArray(payload.items));
  assert.equal(typeof payload.honesty, 'string');
  assert.ok(payload.honesty.length > 0);
});

test('specProxy builds a mountable plugin', () => {
  const plugin = specProxy('euro-paris-parking-garages', SPEC);
  assert.equal(plugin.name, 'euro-paris-parking-garages');
  assert.equal(typeof plugin.configureServer, 'function');
});

test('every mapped $-path is syntactically valid', () => {
  for (const p of Object.values(spec.extract.map)) {
    assert.ok(resolvePath({ a: 1 }, '$') !== undefined); // resolver alive
    assert.match(p, /^\$/);
  }
  assert.match(spec.extract.items, /^\$/);
});
