/**
 * @module themes
 * @description The 14 Reality OS HUD skin manifests.
 *
 * Each manifest: display name/tagline, CSS custom properties (bg, panel,
 * accent, text, warn, ok, danger, info, fonts), effects flags, chrome notes,
 * and a full terminology dictionary covering every key in KEYS.md.
 *
 * Constraints honored: no copyrighted assets (pure CSS/SVG, system fonts
 * only), data values never change — only words, palette, typography, chrome.
 */

const MONO = `'Courier New', ui-monospace, Menlo, Consolas, monospace`;
const UI_SANS = `system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif`;
const SERIF = `Georgia, 'Times New Roman', serif`;
const CONDENSED = `'Arial Narrow', 'Helvetica Neue Condensed', Impact, sans-serif`;

/**
 * @typedef {Object} ThemeManifest
 * @property {string} id
 * @property {string} name
 * @property {string} tagline
 * @property {{bg:string,panel:string,accent:string,text:string,warn:string,ok:string,danger:string,info:string,fontUi:string,fontMono:string}} vars
 * @property {string[]} effects - subset of scanlines|vignette|noise|phosphorGlow|hologramFlicker|glitch
 * @property {string} chrome - notes on the intended chrome treatment
 * @property {Record<string,string>} strings - full dictionary (KEYS.md)
 */

/** @type {ThemeManifest[]} */
export const THEMES = [
  {
    id: 'medbay',
    name: 'Med-Bay',
    tagline: 'Patient: Earth — vitals nominal',
    vars: {
      bg: '#0a0f14',
      panel: '#101820',
      accent: '#4dd0a6',
      text: '#d8f3e8',
      warn: '#ffb454',
      ok: '#4dd0a6',
      danger: '#ff5a5a',
      info: '#6ec6ff',
      fontUi: UI_SANS,
      fontMono: MONO,
    },
    effects: ['vignette', 'phosphorGlow'],
    chrome:
      'Rounded vitals cards, thin mint telemetry lines, heartbeat pulse on live readouts.',
    strings: {
      'app.title': 'PLANETARY TRIAGE',
      'app.tagline': 'Patient: Earth — vitals nominal',
      'layer.firms': 'Fever spots (FIRMS)',
      'layer.earthquakes': 'Tremors (USGS)',
      'layer.flights': 'Circulation traffic (ADS-B)',
      'layer.vessels': 'Bloodstream vessels (AIS)',
      'layer.satellites': 'Implants (TLE)',
      'layer.weather': 'Skin conditions (GIBS)',
      'layer.cyclones': 'Respiratory events',
      'layer.volcanoes': 'Eruptions',
      'layer.aurora': 'Neural shimmer',
      'layer.lightning': 'Static discharges',
      'layer.smoke': 'Smoke inhalation (HMS)',
      'layer.radar': 'Ultrasound (RainViewer)',
      'feature.events': 'Symptom log',
      'feature.dvr': 'Chart history',
      'feature.seismic': 'Tremor propagation',
      'feature.lightning': 'Static discharge map',
      'feature.ovation': 'Neural shimmer forecast',
      'feature.skyAnomaly': 'Anomalous readings',
      'feature.nlq': 'Ask the physician',
      'feature.sonification': 'Auscultation',
      'feature.forecastFireSpread': 'Fever-spread prognosis',
      'feature.forecastHurricaneCones': 'Respiratory cone prognosis',
      'feature.forecastAsh': 'Ashfall prognosis',
      'feature.notebook': 'Patient chart',
      'feature.indoorTwin': 'Ward view',
      'feature.autoBriefing': 'Morning rounds',
      'severity.low': 'Stable',
      'severity.moderate': 'Elevated',
      'severity.high': 'Critical',
      'severity.critical': 'Code blue',
      'incident.label': 'Episode',
      'alert.label': 'Page',
          'feature.akashic': "Planetary memory",
      'ui.akashic.open': "\u25c8 records",
      'ui.akashic.replayDay': "\u25b6 replay the day",
      'ui.akashic.viewInDvr': "view in GIBS DVR",
      'ui.akashic.noDays': "no archived days yet",
      'feature.webxr': "Inside the planet",
      'ui.webxr.enter': "\u25c9 step inside the planet (v1)",
      'ui.webxr.fallbackTitle': "\u25c8 inside the planet \u2014 360 viewer",
      'ui.webxr.fallbackNote': "(non-XR fallback; drag to look around)",
      'feature.gaiaVoice': "Planetary voice",
      'ui.gaia.listening': "\ud83d\udd0a gaia listening",
      'ui.gaia.muted': "\ud83d\udd07 gaia muted",
      'ui.gaia.test': "test voice",
      'feature.sharedEye': "Shared view",
      'ui.sharedEye.open': "\u25c8 shared eye",
      'ui.sharedEye.create': "create session",
      'ui.sharedEye.join': "join session",
      'ui.sharedEye.followMode': "follow-mode (no P2P needed)",
      'feature.interplanetary': "Interplanetary",
      'feature.planetaryDefense': "Planetary defense",
      'feature.eyesOn': "Eyes-on countdown",
      'feature.gravWaves': "Spacetime ripples",
      'feature.nwisGauges': "River gauges (USGS)",
      'feature.nwps': "Flood-wave forecast (NWM)",
      'feature.airQuality': "Air-quality haze (citizen sensors)",
      'feature.spaceWeather': "Space weather (Kp)",
      'feature.donki': "Solar storms (DONKI)",
      'feature.cableThreat': "Cable-threat correlation",
      'feature.nwsAlerts': "NWS alert polygons",
      'feature.sigmets': "Aviation SIGMETs",
      'feature.asteroids': "Asteroid flybys",
      'feature.biosphere': "Biosphere ticker",
      'feature.carbon': "Grid carbon intensity",
      'feature.certs': "Certificate transparency",
      'feature.civic': "Civic ticker",
      'feature.co2': "CO₂ (Mauna Loa)",
      'feature.felt': "Felt earthquakes (EMSC)",
      'feature.hazards': "Multi-hazard events (GDACS)",
      'feature.markets': "Markets (FX · BTC)",
      'feature.pota': "Who's on the air (POTA)",
      'feature.quakes': "Global quakes (5-catalog)",
      'feature.radioRef': "Radio reference",
      'feature.research': "Research ticker",
      'feature.satnogs': "Ground stations (SatNOGS)",
      'feature.uv': "UV index",
      'feature.volcano': "Volcano alerts (GeoNet + AVO)",
      'feature.terminatorRush': "Terminator Rush",
      'feature.deepTime': "Deep time (paleogeography)",
      'feature.oceanTwin': "Ocean twin (currents \u00b7 cables \u00b7 Argo)",
      'feature.whatIf': "What-if simulator (effect rings)",
      'feature.radiation': "Radiation map (Safecast)",
      'feature.dartCoupling': "DART tsunami coupling",
      'feature.waterTwin': "Water twin \u2014 reservoirs & rivers",
      'feature.watchReplay': "Watch queries + day replay",
      'feature.quakeImpact': "Quake impact \u2014 felt & shaking",
      'feature.ripestat': "Routing pulse (RIPEstat)",
      'feature.ripestat.collector': "RIS collector",
      'feature.ripestat.originAs': "Origin AS",
      'feature.feodo': "Botnet C2 map (Feodo)",
      'feature.feodo.online': "C2 currently online",
      'feature.feodo.offline': "Historical / offline listings",
      'feature.gdelt': "Planetary attention (GDELT)",
      'feature.gdelt.positive': "Positive tone",
      'feature.gdelt.neutral': "Neutral tone",
      'feature.gdelt.negative': "Negative tone",
      'feature.meteors': "Night-side meteors (GMN)",
      'feature.meteors.velocity': "Entry velocity",
      'feature.meteors.mass': "Estimated mass",
      'feature.eibi': "Shortwave on air (EiBi)",
      'feature.eibi.onAir': "on air now",
      'feature.eibi.site': "Transmitter site code",
      'feature.aishub': "AIS receiver mesh (AISHub)",
      'feature.aishub.live': "Heard within the hour",
      'feature.aishub.day': "Heard today",
      'feature.aishub.stale': "Silent over a day",
      'feature.fireballs': "Fireball impacts",
      'feature.conjunctions': "Conjunction theater",
      'feature.reentry': "Reentry watch",
      'feature.cosmicRay': "Cosmic-ray weather",
      'feature.wxstations': "Station vitals",
      'feature.time': "Clock standard",
},
  },
  {
    id: 'batcave',
    name: 'Batcave Protocol',
    tagline: 'All assets accounted for. The city sleeps; the watch does not.',
    vars: {
      bg: '#050505',
      panel: '#0d0d10',
      accent: '#ffb000',
      text: '#cfd2d6',
      warn: '#ffb000',
      ok: '#39d353',
      danger: '#ff3b30',
      info: '#58a6ff',
      fontUi: CONDENSED,
      fontMono: MONO,
    },
    effects: ['vignette', 'noise'],
    chrome:
      'Deep-black panels, amber readouts, asset dossiers with red-string connectors.',
    strings: {
      'app.title': 'CAVE SYSTEMS',
      'app.tagline': 'All assets accounted for',
      'layer.firms': 'Fire signatures (FIRMS)',
      'layer.earthquakes': 'Ground disturbances (USGS)',
      'layer.flights': 'Airborne assets (ADS-B)',
      'layer.vessels': 'Maritime assets (AIS)',
      'layer.satellites': 'Orbital assets (TLE)',
      'layer.weather': 'Atmospheric conditions (GIBS)',
      'layer.cyclones': 'Storm hostiles',
      'layer.volcanoes': 'Thermal anomalies',
      'layer.aurora': 'Ionospheric veil',
      'layer.lightning': 'Electrical discharges',
      'layer.smoke': 'Obscurants (HMS)',
      'layer.radar': 'Sweep (RainViewer)',
      'feature.events': 'Incident ledger',
      'feature.dvr': 'Archive playback',
      'feature.seismic': 'Shockwave tracking',
      'feature.lightning': 'Discharge grid',
      'feature.ovation': 'Ionospheric veil forecast',
      'feature.skyAnomaly': 'Unidentified contacts',
      'feature.nlq': 'Interrogate the archive',
      'feature.sonification': 'Audio surveillance',
      'feature.forecastFireSpread': 'Fire-front projection',
      'feature.forecastHurricaneCones': 'Storm-track projection',
      'feature.forecastAsh': 'Ashfall projection',
      'feature.notebook': 'Case files',
      'feature.indoorTwin': 'Interior schematic',
      'feature.autoBriefing': 'Nightly debrief',
      'severity.low': 'Cold trail',
      'severity.moderate': 'Warm trail',
      'severity.high': 'Hot',
      'severity.critical': 'Code black',
      'incident.label': 'Case',
      'alert.label': 'Signal',
          'feature.akashic': "Planetary memory",
      'ui.akashic.open': "\u25c8 records",
      'ui.akashic.replayDay': "\u25b6 replay the day",
      'ui.akashic.viewInDvr': "view in GIBS DVR",
      'ui.akashic.noDays': "no archived days yet",
      'feature.webxr': "Inside the planet",
      'ui.webxr.enter': "\u25c9 step inside the planet (v1)",
      'ui.webxr.fallbackTitle': "\u25c8 inside the planet \u2014 360 viewer",
      'ui.webxr.fallbackNote': "(non-XR fallback; drag to look around)",
      'feature.gaiaVoice': "Planetary voice",
      'ui.gaia.listening': "\ud83d\udd0a gaia listening",
      'ui.gaia.muted': "\ud83d\udd07 gaia muted",
      'ui.gaia.test': "test voice",
      'feature.sharedEye': "Shared view",
      'ui.sharedEye.open': "\u25c8 shared eye",
      'ui.sharedEye.create': "create session",
      'ui.sharedEye.join': "join session",
      'ui.sharedEye.followMode': "follow-mode (no P2P needed)",
      'feature.interplanetary': "Interplanetary",
      'feature.planetaryDefense': "Planetary defense",
      'feature.eyesOn': "Eyes-on countdown",
      'feature.gravWaves': "Spacetime ripples",
      'feature.nwisGauges': "River gauges (USGS)",
      'feature.nwps': "Flood-wave forecast (NWM)",
      'feature.airQuality': "Air-quality haze (citizen sensors)",
      'feature.spaceWeather': "Space weather (Kp)",
      'feature.donki': "Solar storms (DONKI)",
      'feature.cableThreat': "Cable-threat correlation",
      'feature.nwsAlerts': "NWS alert polygons",
      'feature.sigmets': "Aviation SIGMETs",
      'feature.asteroids': "Asteroid flybys",
      'feature.biosphere': "Biosphere ticker",
      'feature.carbon': "Grid carbon intensity",
      'feature.certs': "Certificate transparency",
      'feature.civic': "Civic ticker",
      'feature.co2': "CO₂ (Mauna Loa)",
      'feature.felt': "Felt earthquakes (EMSC)",
      'feature.hazards': "Multi-hazard events (GDACS)",
      'feature.markets': "Markets (FX · BTC)",
      'feature.pota': "Who's on the air (POTA)",
      'feature.quakes': "Global quakes (5-catalog)",
      'feature.radioRef': "Radio reference",
      'feature.research': "Research ticker",
      'feature.satnogs': "Ground stations (SatNOGS)",
      'feature.uv': "UV index",
      'feature.volcano': "Volcano alerts (GeoNet + AVO)",
      'feature.terminatorRush': "Terminator Rush",
      'feature.deepTime': "Deep time (paleogeography)",
      'feature.oceanTwin': "Ocean twin (currents \u00b7 cables \u00b7 Argo)",
      'feature.whatIf': "What-if simulator (effect rings)",
      'feature.radiation': "Radiation map (Safecast)",
      'feature.dartCoupling': "DART tsunami coupling",
      'feature.waterTwin': "Water twin \u2014 reservoirs & rivers",
      'feature.watchReplay': "Watch queries + day replay",
      'feature.quakeImpact': "Quake impact \u2014 felt & shaking",
      'feature.ripestat': "Routing pulse (RIPEstat)",
      'feature.ripestat.collector': "RIS collector",
      'feature.ripestat.originAs': "Origin AS",
      'feature.feodo': "Botnet C2 map (Feodo)",
      'feature.feodo.online': "C2 currently online",
      'feature.feodo.offline': "Historical / offline listings",
      'feature.gdelt': "Planetary attention (GDELT)",
      'feature.gdelt.positive': "Positive tone",
      'feature.gdelt.neutral': "Neutral tone",
      'feature.gdelt.negative': "Negative tone",
      'feature.meteors': "Night-side meteors (GMN)",
      'feature.meteors.velocity': "Entry velocity",
      'feature.meteors.mass': "Estimated mass",
      'feature.eibi': "Shortwave on air (EiBi)",
      'feature.eibi.onAir': "on air now",
      'feature.eibi.site': "Transmitter site code",
      'feature.aishub': "AIS receiver mesh (AISHub)",
      'feature.aishub.live': "Heard within the hour",
      'feature.aishub.day': "Heard today",
      'feature.aishub.stale': "Silent over a day",
      'feature.fireballs': "Fireball impacts",
      'feature.conjunctions': "Conjunction theater",
      'feature.reentry': "Reentry watch",
      'feature.cosmicRay': "Cosmic-ray weather",
      'feature.wxstations': "Weather station grid",
      'feature.time': "Time standard watch",
},
  },
  {
    id: 'garage',
    name: "Rick's Garage",
    tagline: 'Science! The planet is fine. Probably. Mostly.',
    vars: {
      bg: '#0b1f0e',
      panel: '#122b16',
      accent: '#39ff6a',
      text: '#e8ffe8',
      warn: '#ffd23f',
      ok: '#39ff6a',
      danger: '#ff4d4d',
      info: '#7fd4ff',
      fontUi: UI_SANS,
      fontMono: MONO,
    },
    effects: ['scanlines', 'glitch'],
    chrome:
      'Duct-taped panels, portal-green readouts, sticky-note annotations, zero respect for whitespace.',
    strings: {
      'app.title': 'GARAGE PLANET-O-MATIC',
      'app.tagline': 'Science! The planet is fine. Probably.',
      'layer.firms': 'Fires (FIRMS) — spicy dots',
      'layer.earthquakes': 'Quakes (USGS) — wibbly bits',
      'layer.flights': 'Planes (ADS-B)',
      'layer.vessels': 'Boats (AIS)',
      'layer.satellites': 'Space junk with jobs (TLE)',
      'layer.weather': 'Sky soup (GIBS)',
      'layer.cyclones': 'Spinny boys',
      'layer.volcanoes': 'Mountain sneezes',
      'layer.aurora': 'Sky glitter',
      'layer.lightning': 'Zap map',
      'layer.smoke': 'Haze (HMS)',
      'layer.radar': 'Rain blobs (RainViewer)',
      'feature.events': 'Weird-stuff ticker',
      'feature.dvr': 'Time machine (no paradoxes)',
      'feature.seismic': 'Wibble waves',
      'feature.lightning': 'Zap map deluxe',
      'feature.ovation': 'Sky-glitter forecast',
      'feature.skyAnomaly': 'Huh, look at that',
      'feature.nlq': 'Ask the genius',
      'feature.sonification': 'Planet noises',
      'feature.forecastFireSpread': 'Where the spicy goes',
      'feature.forecastHurricaneCones': 'Spinny-boy cones',
      'feature.forecastAsh': 'Ash forecast (wear goggles)',
      'feature.notebook': 'Napkin sketches',
      'feature.indoorTwin': 'Dollhouse mode',
      'feature.autoBriefing': 'Morning science rant',
      'severity.low': 'Meh',
      'severity.moderate': 'Hmm',
      'severity.high': 'Yikes',
      'severity.critical': 'OH NO',
      'incident.label': 'Thing',
      'alert.label': 'Heads-up',
          'feature.akashic': "Planetary memory",
      'ui.akashic.open': "\u25c8 records",
      'ui.akashic.replayDay': "\u25b6 replay the day",
      'ui.akashic.viewInDvr': "view in GIBS DVR",
      'ui.akashic.noDays': "no archived days yet",
      'feature.webxr': "Inside the planet",
      'ui.webxr.enter': "\u25c9 step inside the planet (v1)",
      'ui.webxr.fallbackTitle': "\u25c8 inside the planet \u2014 360 viewer",
      'ui.webxr.fallbackNote': "(non-XR fallback; drag to look around)",
      'feature.gaiaVoice': "Planetary voice",
      'ui.gaia.listening': "\ud83d\udd0a gaia listening",
      'ui.gaia.muted': "\ud83d\udd07 gaia muted",
      'ui.gaia.test': "test voice",
      'feature.sharedEye': "Shared view",
      'ui.sharedEye.open': "\u25c8 shared eye",
      'ui.sharedEye.create': "create session",
      'ui.sharedEye.join': "join session",
      'ui.sharedEye.followMode': "follow-mode (no P2P needed)",
      'feature.interplanetary': "Interplanetary",
      'feature.planetaryDefense': "Planetary defense",
      'feature.eyesOn': "Eyes-on countdown",
      'feature.gravWaves': "Spacetime ripples",
      'feature.nwisGauges': "River gauges (USGS)",
      'feature.nwps': "Flood-wave forecast (NWM)",
      'feature.airQuality': "Air-quality haze (citizen sensors)",
      'feature.spaceWeather': "Space weather (Kp)",
      'feature.donki': "Solar storms (DONKI)",
      'feature.cableThreat': "Cable-threat correlation",
      'feature.nwsAlerts': "NWS alert polygons",
      'feature.sigmets': "Aviation SIGMETs",
      'feature.asteroids': "Asteroid flybys",
      'feature.biosphere': "Biosphere ticker",
      'feature.carbon': "Grid carbon intensity",
      'feature.certs': "Certificate transparency",
      'feature.civic': "Civic ticker",
      'feature.co2': "CO₂ (Mauna Loa)",
      'feature.felt': "Felt earthquakes (EMSC)",
      'feature.hazards': "Multi-hazard events (GDACS)",
      'feature.markets': "Markets (FX · BTC)",
      'feature.pota': "Who's on the air (POTA)",
      'feature.quakes': "Global quakes (5-catalog)",
      'feature.radioRef': "Radio reference",
      'feature.research': "Research ticker",
      'feature.satnogs': "Ground stations (SatNOGS)",
      'feature.uv': "UV index",
      'feature.volcano': "Volcano alerts (GeoNet + AVO)",
      'feature.terminatorRush': "Terminator Rush",
      'feature.deepTime': "Deep time (paleogeography)",
      'feature.oceanTwin': "Ocean twin (currents \u00b7 cables \u00b7 Argo)",
      'feature.whatIf': "What-if simulator (effect rings)",
      'feature.radiation': "Radiation map (Safecast)",
      'feature.dartCoupling': "DART tsunami coupling",
      'feature.waterTwin': "Water twin \u2014 reservoirs & rivers",
      'feature.watchReplay': "Watch queries + day replay",
      'feature.quakeImpact': "Quake impact \u2014 felt & shaking",
      'feature.ripestat': "Routing pulse (RIPEstat)",
      'feature.ripestat.collector': "RIS collector",
      'feature.ripestat.originAs': "Origin AS",
      'feature.feodo': "Botnet C2 map (Feodo)",
      'feature.feodo.online': "C2 currently online",
      'feature.feodo.offline': "Historical / offline listings",
      'feature.gdelt': "Planetary attention (GDELT)",
      'feature.gdelt.positive': "Positive tone",
      'feature.gdelt.neutral': "Neutral tone",
      'feature.gdelt.negative': "Negative tone",
      'feature.meteors': "Night-side meteors (GMN)",
      'feature.meteors.velocity': "Entry velocity",
      'feature.meteors.mass': "Estimated mass",
      'feature.eibi': "Shortwave on air (EiBi)",
      'feature.eibi.onAir': "on air now",
      'feature.eibi.site': "Transmitter site code",
      'feature.aishub': "AIS receiver mesh (AISHub)",
      'feature.aishub.live': "Heard within the hour",
      'feature.aishub.day': "Heard today",
      'feature.aishub.stale': "Silent over a day",
      'feature.fireballs': "Fireball impacts",
      'feature.conjunctions': "Conjunction theater",
      'feature.reentry': "Reentry watch",
      'feature.cosmicRay': "Cosmic-ray weather",
      'feature.wxstations': "Weather stations",
      'feature.time': "Time standards",
},
  },
  {
    id: 'noir',
    name: 'Noir Files',
    tagline:
      'Every incident is a case. The planet always talks — you just have to listen.',
    vars: {
      bg: '#0e0c0a',
      panel: '#171310',
      accent: '#d8b25c',
      text: '#e8ddc8',
      warn: '#e08e45',
      ok: '#9dbb7a',
      danger: '#c0392b',
      info: '#8fa3b8',
      fontUi: SERIF,
      fontMono: MONO,
    },
    effects: ['vignette', 'noise'],
    chrome:
      'Sepia case-file cards, red-string pins, typewriter stamps, coffee-ring dividers.',
    strings: {
      'app.title': 'THE NOIR FILES',
      'app.tagline': 'The planet always talks — you just have to listen',
      'layer.firms': 'Arson reports (FIRMS)',
      'layer.earthquakes': 'Underground rumblings (USGS)',
      'layer.flights': 'Departures & arrivals (ADS-B)',
      'layer.vessels': 'Harbor manifests (AIS)',
      'layer.satellites': 'Eyes upstairs (TLE)',
      'layer.weather': 'The weather dame (GIBS)',
      'layer.cyclones': 'Big blows',
      'layer.volcanoes': 'Hot tempers',
      'layer.aurora': 'Neon alibis',
      'layer.lightning': 'Static confessions',
      'layer.smoke': 'Smoke screens (HMS)',
      'layer.radar': 'The long watch (RainViewer)',
      'feature.events': 'The blotter',
      'feature.dvr': 'Cold cases',
      'feature.seismic': 'Aftershock trail',
      'feature.lightning': 'Confession grid',
      'feature.ovation': 'Neon alibi forecast',
      'feature.skyAnomaly': 'Suspicious characters',
      'feature.nlq': 'Ask the informant',
      'feature.sonification': 'Wiretap audio',
      'feature.forecastFireSpread': 'Where the fire goes next',
      'feature.forecastHurricaneCones': "The blow's itinerary",
      'feature.forecastAsh': 'Ashfall testimony',
      'feature.notebook': "The detective's notebook",
      'feature.indoorTwin': 'The floor plan',
      'feature.autoBriefing': 'Morning edition',
      'severity.low': 'A whisper',
      'severity.moderate': 'A rumor',
      'severity.high': 'A scream',
      'severity.critical': 'A gunshot',
      'incident.label': 'Case',
      'alert.label': 'Tip-off',
          'feature.akashic': "Planetary memory",
      'ui.akashic.open': "\u25c8 records",
      'ui.akashic.replayDay': "\u25b6 replay the day",
      'ui.akashic.viewInDvr': "view in GIBS DVR",
      'ui.akashic.noDays': "no archived days yet",
      'feature.webxr': "Inside the planet",
      'ui.webxr.enter': "\u25c9 step inside the planet (v1)",
      'ui.webxr.fallbackTitle': "\u25c8 inside the planet \u2014 360 viewer",
      'ui.webxr.fallbackNote': "(non-XR fallback; drag to look around)",
      'feature.gaiaVoice': "Planetary voice",
      'ui.gaia.listening': "\ud83d\udd0a gaia listening",
      'ui.gaia.muted': "\ud83d\udd07 gaia muted",
      'ui.gaia.test': "test voice",
      'feature.sharedEye': "Shared view",
      'ui.sharedEye.open': "\u25c8 shared eye",
      'ui.sharedEye.create': "create session",
      'ui.sharedEye.join': "join session",
      'ui.sharedEye.followMode': "follow-mode (no P2P needed)",
      'feature.interplanetary': "Interplanetary",
      'feature.planetaryDefense': "Planetary defense",
      'feature.eyesOn': "Eyes-on countdown",
      'feature.gravWaves': "Spacetime ripples",
      'feature.nwisGauges': "River gauges (USGS)",
      'feature.nwps': "Flood-wave forecast (NWM)",
      'feature.airQuality': "Air-quality haze (citizen sensors)",
      'feature.spaceWeather': "Space weather (Kp)",
      'feature.donki': "Solar storms (DONKI)",
      'feature.cableThreat': "Cable-threat correlation",
      'feature.nwsAlerts': "NWS alert polygons",
      'feature.sigmets': "Aviation SIGMETs",
      'feature.asteroids': "Asteroid flybys",
      'feature.biosphere': "Biosphere ticker",
      'feature.carbon': "Grid carbon intensity",
      'feature.certs': "Certificate transparency",
      'feature.civic': "Civic ticker",
      'feature.co2': "CO₂ (Mauna Loa)",
      'feature.felt': "Felt earthquakes (EMSC)",
      'feature.hazards': "Multi-hazard events (GDACS)",
      'feature.markets': "Markets (FX · BTC)",
      'feature.pota': "Who's on the air (POTA)",
      'feature.quakes': "Global quakes (5-catalog)",
      'feature.radioRef': "Radio reference",
      'feature.research': "Research ticker",
      'feature.satnogs': "Ground stations (SatNOGS)",
      'feature.uv': "UV index",
      'feature.volcano': "Volcano alerts (GeoNet + AVO)",
      'feature.terminatorRush': "Terminator Rush",
      'feature.deepTime': "Deep time (paleogeography)",
      'feature.oceanTwin': "Ocean twin (currents \u00b7 cables \u00b7 Argo)",
      'feature.whatIf': "What-if simulator (effect rings)",
      'feature.radiation': "Radiation map (Safecast)",
      'feature.dartCoupling': "DART tsunami coupling",
      'feature.waterTwin': "Water twin \u2014 reservoirs & rivers",
      'feature.watchReplay': "Watch queries + day replay",
      'feature.quakeImpact': "Quake impact \u2014 felt & shaking",
      'feature.ripestat': "Routing pulse (RIPEstat)",
      'feature.ripestat.collector': "RIS collector",
      'feature.ripestat.originAs': "Origin AS",
      'feature.feodo': "Botnet C2 map (Feodo)",
      'feature.feodo.online': "C2 currently online",
      'feature.feodo.offline': "Historical / offline listings",
      'feature.gdelt': "Planetary attention (GDELT)",
      'feature.gdelt.positive': "Positive tone",
      'feature.gdelt.neutral': "Neutral tone",
      'feature.gdelt.negative': "Negative tone",
      'feature.meteors': "Night-side meteors (GMN)",
      'feature.meteors.velocity': "Entry velocity",
      'feature.meteors.mass': "Estimated mass",
      'feature.eibi': "Shortwave on air (EiBi)",
      'feature.eibi.onAir': "on air now",
      'feature.eibi.site': "Transmitter site code",
      'feature.aishub': "AIS receiver mesh (AISHub)",
      'feature.aishub.live': "Heard within the hour",
      'feature.aishub.day': "Heard today",
      'feature.aishub.stale': "Silent over a day",
      'feature.fireballs': "Fireball impacts",
      'feature.conjunctions': "Conjunction theater",
      'feature.reentry': "Reentry watch",
      'feature.cosmicRay': "Cosmic-ray weather",
      'feature.wxstations': "Station reports",
      'feature.time': "Chronometer file",
},
  },
  {
    id: 'lcars',
    name: 'LCARS',
    tagline: 'Library computer access and retrieval. All systems nominal.',
    vars: {
      bg: '#080810',
      panel: '#101018',
      accent: '#ffcc99',
      text: '#e6e6fa',
      warn: '#ffcc66',
      ok: '#99cc99',
      danger: '#cc6666',
      info: '#9999ff',
      fontUi: CONDENSED,
      fontMono: MONO,
    },
    effects: ['phosphorGlow'],
    chrome:
      'Pastel lozenge buttons, elbow-frame panel corners, precise grid alignment.',
    strings: {
      'app.title': 'PLANETARY STATUS DISPLAY',
      'app.tagline': 'Library computer access and retrieval',
      'layer.firms': 'Combustion events (FIRMS)',
      'layer.earthquakes': 'Seismic events (USGS)',
      'layer.flights': 'Atmospheric vehicles (ADS-B)',
      'layer.vessels': 'Surface vessels (AIS)',
      'layer.satellites': 'Orbital platforms (TLE)',
      'layer.weather': 'Meteorological overlay (GIBS)',
      'layer.cyclones': 'Cyclonic systems',
      'layer.volcanoes': 'Volcanic events',
      'layer.aurora': 'Auroral activity',
      'layer.lightning': 'Electrical discharges',
      'layer.smoke': 'Particulate plumes (HMS)',
      'layer.radar': 'Precipitation scan (RainViewer)',
      'feature.events': 'Event synthesis',
      'feature.dvr': 'Temporal archive',
      'feature.seismic': 'Wavefront propagation',
      'feature.lightning': 'Discharge overlay',
      'feature.ovation': 'Auroral prediction',
      'feature.skyAnomaly': 'Anomaly advisories',
      'feature.nlq': 'Computer, query',
      'feature.sonification': 'Acoustic rendering',
      'feature.forecastFireSpread': 'Combustion projection',
      'feature.forecastHurricaneCones': 'Cyclone track projection',
      'feature.forecastAsh': 'Ejecta projection',
      'feature.notebook': 'Research log',
      'feature.indoorTwin': 'Interior schematic',
      'feature.autoBriefing': 'Daily summary',
      'severity.low': 'Advisory',
      'severity.moderate': 'Caution',
      'severity.high': 'Warning',
      'severity.critical': 'Emergency',
      'incident.label': 'Event',
      'alert.label': 'Notice',
          'feature.akashic': "Planetary memory",
      'ui.akashic.open': "\u25c8 records",
      'ui.akashic.replayDay': "\u25b6 replay the day",
      'ui.akashic.viewInDvr': "view in GIBS DVR",
      'ui.akashic.noDays': "no archived days yet",
      'feature.webxr': "Inside the planet",
      'ui.webxr.enter': "\u25c9 step inside the planet (v1)",
      'ui.webxr.fallbackTitle': "\u25c8 inside the planet \u2014 360 viewer",
      'ui.webxr.fallbackNote': "(non-XR fallback; drag to look around)",
      'feature.gaiaVoice': "Planetary voice",
      'ui.gaia.listening': "\ud83d\udd0a gaia listening",
      'ui.gaia.muted': "\ud83d\udd07 gaia muted",
      'ui.gaia.test': "test voice",
      'feature.sharedEye': "Shared view",
      'ui.sharedEye.open': "\u25c8 shared eye",
      'ui.sharedEye.create': "create session",
      'ui.sharedEye.join': "join session",
      'ui.sharedEye.followMode': "follow-mode (no P2P needed)",
      'feature.interplanetary': "Interplanetary",
      'feature.planetaryDefense': "Planetary defense",
      'feature.eyesOn': "Eyes-on countdown",
      'feature.gravWaves': "Spacetime ripples",
      'feature.nwisGauges': "River gauges (USGS)",
      'feature.nwps': "Flood-wave forecast (NWM)",
      'feature.airQuality': "Air-quality haze (citizen sensors)",
      'feature.spaceWeather': "Space weather (Kp)",
      'feature.donki': "Solar storms (DONKI)",
      'feature.cableThreat': "Cable-threat correlation",
      'feature.nwsAlerts': "NWS alert polygons",
      'feature.sigmets': "Aviation SIGMETs",
      'feature.asteroids': "Asteroid flybys",
      'feature.biosphere': "Biosphere ticker",
      'feature.carbon': "Grid carbon intensity",
      'feature.certs': "Certificate transparency",
      'feature.civic': "Civic ticker",
      'feature.co2': "CO₂ (Mauna Loa)",
      'feature.felt': "Felt earthquakes (EMSC)",
      'feature.hazards': "Multi-hazard events (GDACS)",
      'feature.markets': "Markets (FX · BTC)",
      'feature.pota': "Who's on the air (POTA)",
      'feature.quakes': "Global quakes (5-catalog)",
      'feature.radioRef': "Radio reference",
      'feature.research': "Research ticker",
      'feature.satnogs': "Ground stations (SatNOGS)",
      'feature.uv': "UV index",
      'feature.volcano': "Volcano alerts (GeoNet + AVO)",
      'feature.terminatorRush': "Terminator Rush",
      'feature.deepTime': "Deep time (paleogeography)",
      'feature.oceanTwin': "Ocean twin (currents \u00b7 cables \u00b7 Argo)",
      'feature.whatIf': "What-if simulator (effect rings)",
      'feature.radiation': "Radiation map (Safecast)",
      'feature.dartCoupling': "DART tsunami coupling",
      'feature.waterTwin': "Water twin \u2014 reservoirs & rivers",
      'feature.watchReplay': "Watch queries + day replay",
      'feature.quakeImpact': "Quake impact \u2014 felt & shaking",
      'feature.ripestat': "Routing pulse (RIPEstat)",
      'feature.ripestat.collector': "RIS collector",
      'feature.ripestat.originAs': "Origin AS",
      'feature.feodo': "Botnet C2 map (Feodo)",
      'feature.feodo.online': "C2 currently online",
      'feature.feodo.offline': "Historical / offline listings",
      'feature.gdelt': "Planetary attention (GDELT)",
      'feature.gdelt.positive': "Positive tone",
      'feature.gdelt.neutral': "Neutral tone",
      'feature.gdelt.negative': "Negative tone",
      'feature.meteors': "Night-side meteors (GMN)",
      'feature.meteors.velocity': "Entry velocity",
      'feature.meteors.mass': "Estimated mass",
      'feature.eibi': "Shortwave on air (EiBi)",
      'feature.eibi.onAir': "on air now",
      'feature.eibi.site': "Transmitter site code",
      'feature.aishub': "AIS receiver mesh (AISHub)",
      'feature.aishub.live': "Heard within the hour",
      'feature.aishub.day': "Heard today",
      'feature.aishub.stale': "Silent over a day",
      'feature.fireballs': "Fireball impacts",
      'feature.conjunctions': "Conjunction theater",
      'feature.reentry': "Reentry watch",
      'feature.cosmicRay': "Cosmic-ray weather",
      'feature.wxstations': "Planetary station net",
      'feature.time': "Temporal reference",
},
  },
  {
    id: 'pipboy',
    name: 'Pip-Boy',
    tagline:
      "Gee whiz, the planet's seen better days! Stay hydrated out there.",
    vars: {
      bg: '#04140a',
      panel: '#06180c',
      accent: '#33ff66',
      text: '#aaffbb',
      warn: '#ffff66',
      ok: '#33ff66',
      danger: '#ff6666',
      info: '#66ffcc',
      fontUi: MONO,
      fontMono: MONO,
    },
    effects: ['scanlines', 'phosphorGlow', 'vignette'],
    chrome:
      'Chunky pixel borders, chunky tabs, cheerful status pips, rounded CRT bezel.',
    strings: {
      'app.title': 'PIP-GLOBE 3000',
      'app.tagline': "Gee whiz! The planet's seen better days!",
      'layer.firms': 'Fires (FIRMS)',
      'layer.earthquakes': 'Quakes (USGS)',
      'layer.flights': 'Flyboys (ADS-B)',
      'layer.vessels': 'Boats (AIS)',
      'layer.satellites': 'Sky buddies (TLE)',
      'layer.weather': 'Weather (GIBS)',
      'layer.cyclones': 'Big storms',
      'layer.volcanoes': 'Volcanoes',
      'layer.aurora': 'Pretty lights',
      'layer.lightning': 'Zaps',
      'layer.smoke': 'Smoke (HMS)',
      'layer.radar': 'Rain radar (RainViewer)',
      'feature.events': 'Happenings',
      'feature.dvr': 'Rewind-o-tron',
      'feature.seismic': 'Shake waves',
      'feature.lightning': 'Zap map',
      'feature.ovation': 'Pretty-lights forecast',
      'feature.skyAnomaly': 'Odd sightings',
      'feature.nlq': 'Ask the Pip',
      'feature.sonification': 'Beep-boop mode',
      'feature.forecastFireSpread': 'Fire forecast',
      'feature.forecastHurricaneCones': 'Storm cones',
      'feature.forecastAsh': 'Ash forecast',
      'feature.notebook': 'Journal',
      'feature.indoorTwin': 'Indoor map',
      'feature.autoBriefing': 'Morning announcements',
      'severity.low': 'No biggie',
      'severity.moderate': 'Keep an eye out',
      'severity.high': 'Uh oh',
      'severity.critical': 'Yikes-a-rooney',
      'incident.label': 'Situation',
      'alert.label': 'Heads-up',
          'feature.akashic': "Planetary memory",
      'ui.akashic.open': "\u25c8 records",
      'ui.akashic.replayDay': "\u25b6 replay the day",
      'ui.akashic.viewInDvr': "view in GIBS DVR",
      'ui.akashic.noDays': "no archived days yet",
      'feature.webxr': "Inside the planet",
      'ui.webxr.enter': "\u25c9 step inside the planet (v1)",
      'ui.webxr.fallbackTitle': "\u25c8 inside the planet \u2014 360 viewer",
      'ui.webxr.fallbackNote': "(non-XR fallback; drag to look around)",
      'feature.gaiaVoice': "Planetary voice",
      'ui.gaia.listening': "\ud83d\udd0a gaia listening",
      'ui.gaia.muted': "\ud83d\udd07 gaia muted",
      'ui.gaia.test': "test voice",
      'feature.sharedEye': "Shared view",
      'ui.sharedEye.open': "\u25c8 shared eye",
      'ui.sharedEye.create': "create session",
      'ui.sharedEye.join': "join session",
      'ui.sharedEye.followMode': "follow-mode (no P2P needed)",
      'feature.interplanetary': "Interplanetary",
      'feature.planetaryDefense': "Planetary defense",
      'feature.eyesOn': "Eyes-on countdown",
      'feature.gravWaves': "Spacetime ripples",
      'feature.nwisGauges': "River gauges (USGS)",
      'feature.nwps': "Flood-wave forecast (NWM)",
      'feature.airQuality': "Air-quality haze (citizen sensors)",
      'feature.spaceWeather': "Space weather (Kp)",
      'feature.donki': "Solar storms (DONKI)",
      'feature.cableThreat': "Cable-threat correlation",
      'feature.nwsAlerts': "NWS alert polygons",
      'feature.sigmets': "Aviation SIGMETs",
      'feature.asteroids': "Asteroid flybys",
      'feature.biosphere': "Biosphere ticker",
      'feature.carbon': "Grid carbon intensity",
      'feature.certs': "Certificate transparency",
      'feature.civic': "Civic ticker",
      'feature.co2': "CO₂ (Mauna Loa)",
      'feature.felt': "Felt earthquakes (EMSC)",
      'feature.hazards': "Multi-hazard events (GDACS)",
      'feature.markets': "Markets (FX · BTC)",
      'feature.pota': "Who's on the air (POTA)",
      'feature.quakes': "Global quakes (5-catalog)",
      'feature.radioRef': "Radio reference",
      'feature.research': "Research ticker",
      'feature.satnogs': "Ground stations (SatNOGS)",
      'feature.uv': "UV index",
      'feature.volcano': "Volcano alerts (GeoNet + AVO)",
      'feature.terminatorRush': "Terminator Rush",
      'feature.deepTime': "Deep time (paleogeography)",
      'feature.oceanTwin': "Ocean twin (currents \u00b7 cables \u00b7 Argo)",
      'feature.whatIf': "What-if simulator (effect rings)",
      'feature.radiation': "Radiation map (Safecast)",
      'feature.dartCoupling': "DART tsunami coupling",
      'feature.waterTwin': "Water twin \u2014 reservoirs & rivers",
      'feature.watchReplay': "Watch queries + day replay",
      'feature.quakeImpact': "Quake impact \u2014 felt & shaking",
      'feature.ripestat': "Routing pulse (RIPEstat)",
      'feature.ripestat.collector': "RIS collector",
      'feature.ripestat.originAs': "Origin AS",
      'feature.feodo': "Botnet C2 map (Feodo)",
      'feature.feodo.online': "C2 currently online",
      'feature.feodo.offline': "Historical / offline listings",
      'feature.gdelt': "Planetary attention (GDELT)",
      'feature.gdelt.positive': "Positive tone",
      'feature.gdelt.neutral': "Neutral tone",
      'feature.gdelt.negative': "Negative tone",
      'feature.meteors': "Night-side meteors (GMN)",
      'feature.meteors.velocity': "Entry velocity",
      'feature.meteors.mass': "Estimated mass",
      'feature.eibi': "Shortwave on air (EiBi)",
      'feature.eibi.onAir': "on air now",
      'feature.eibi.site': "Transmitter site code",
      'feature.aishub': "AIS receiver mesh (AISHub)",
      'feature.aishub.live': "Heard within the hour",
      'feature.aishub.day': "Heard today",
      'feature.aishub.stale': "Silent over a day",
      'feature.fireballs': "Fireball impacts",
      'feature.conjunctions': "Conjunction theater",
      'feature.reentry': "Reentry watch",
      'feature.cosmicRay': "Cosmic-ray weather",
      'feature.wxstations': "Weather stations",
      'feature.time': "Time standards",
},
  },
  {
    id: 'jarvis',
    name: 'JARVIS',
    tagline: 'At your service, boss. All systems running at peak efficiency.',
    vars: {
      bg: '#020a12',
      panel: '#06121e',
      accent: '#4db8ff',
      text: '#d6ecff',
      warn: '#ffc857',
      ok: '#5eead4',
      danger: '#ff6b6b',
      info: '#7cc7ff',
      fontUi: UI_SANS,
      fontMono: MONO,
    },
    effects: ['hologramFlicker', 'vignette'],
    chrome:
      'Floating hologram cards, fine blue wireframes, arc-reactor status ring.',
    strings: {
      'app.title': 'GLOBAL INTERFACE',
      'app.tagline': 'At your service, boss',
      'layer.firms': 'Thermal events, boss (FIRMS)',
      'layer.earthquakes': 'Seismic events, boss (USGS)',
      'layer.flights': 'Air traffic, boss (ADS-B)',
      'layer.vessels': 'Maritime traffic, boss (AIS)',
      'layer.satellites': 'Orbital assets, boss (TLE)',
      'layer.weather': 'Weather overlay, boss (GIBS)',
      'layer.cyclones': 'Cyclonic systems, boss',
      'layer.volcanoes': 'Volcanic activity, boss',
      'layer.aurora': 'Auroral display, boss',
      'layer.lightning': 'Electrical activity, boss',
      'layer.smoke': 'Smoke plumes, boss (HMS)',
      'layer.radar': 'Precipitation radar, boss (RainViewer)',
      'feature.events': 'Event digest, boss',
      'feature.dvr': 'Temporal replay, boss',
      'feature.seismic': 'Wavefront tracking, boss',
      'feature.lightning': 'Strike overlay, boss',
      'feature.ovation': 'Aurora forecast, boss',
      'feature.skyAnomaly': 'Anomalies, boss',
      'feature.nlq': 'Ask me anything, boss',
      'feature.sonification': 'Audio readout, boss',
      'feature.forecastFireSpread': 'Fire projection, boss',
      'feature.forecastHurricaneCones': 'Storm cones, boss',
      'feature.forecastAsh': 'Ash projection, boss',
      'feature.notebook': 'Your notes, boss',
      'feature.indoorTwin': 'Interior hologram, boss',
      'feature.autoBriefing': 'Morning briefing, boss',
      'severity.low': 'Nominal, boss',
      'severity.moderate': 'Worth noting, boss',
      'severity.high': 'Elevated concern, boss',
      'severity.critical': 'Immediate attention, boss',
      'incident.label': 'Situation',
      'alert.label': 'Notification',
          'feature.akashic': "Planetary memory",
      'ui.akashic.open': "\u25c8 records",
      'ui.akashic.replayDay': "\u25b6 replay the day",
      'ui.akashic.viewInDvr': "view in GIBS DVR",
      'ui.akashic.noDays': "no archived days yet",
      'feature.webxr': "Inside the planet",
      'ui.webxr.enter': "\u25c9 step inside the planet (v1)",
      'ui.webxr.fallbackTitle': "\u25c8 inside the planet \u2014 360 viewer",
      'ui.webxr.fallbackNote': "(non-XR fallback; drag to look around)",
      'feature.gaiaVoice': "Planetary voice",
      'ui.gaia.listening': "\ud83d\udd0a gaia listening",
      'ui.gaia.muted': "\ud83d\udd07 gaia muted",
      'ui.gaia.test': "test voice",
      'feature.sharedEye': "Shared view",
      'ui.sharedEye.open': "\u25c8 shared eye",
      'ui.sharedEye.create': "create session",
      'ui.sharedEye.join': "join session",
      'ui.sharedEye.followMode': "follow-mode (no P2P needed)",
      'feature.interplanetary': "Interplanetary",
      'feature.planetaryDefense': "Planetary defense",
      'feature.eyesOn': "Eyes-on countdown",
      'feature.gravWaves': "Spacetime ripples",
      'feature.nwisGauges': "River gauges (USGS)",
      'feature.nwps': "Flood-wave forecast (NWM)",
      'feature.airQuality': "Air-quality haze (citizen sensors)",
      'feature.spaceWeather': "Space weather (Kp)",
      'feature.donki': "Solar storms (DONKI)",
      'feature.cableThreat': "Cable-threat correlation",
      'feature.nwsAlerts': "NWS alert polygons",
      'feature.sigmets': "Aviation SIGMETs",
      'feature.asteroids': "Asteroid flybys",
      'feature.biosphere': "Biosphere ticker",
      'feature.carbon': "Grid carbon intensity",
      'feature.certs': "Certificate transparency",
      'feature.civic': "Civic ticker",
      'feature.co2': "CO₂ (Mauna Loa)",
      'feature.felt': "Felt earthquakes (EMSC)",
      'feature.hazards': "Multi-hazard events (GDACS)",
      'feature.markets': "Markets (FX · BTC)",
      'feature.pota': "Who's on the air (POTA)",
      'feature.quakes': "Global quakes (5-catalog)",
      'feature.radioRef': "Radio reference",
      'feature.research': "Research ticker",
      'feature.satnogs': "Ground stations (SatNOGS)",
      'feature.uv': "UV index",
      'feature.volcano': "Volcano alerts (GeoNet + AVO)",
      'feature.terminatorRush': "Terminator Rush",
      'feature.deepTime': "Deep time (paleogeography)",
      'feature.oceanTwin': "Ocean twin (currents \u00b7 cables \u00b7 Argo)",
      'feature.whatIf': "What-if simulator (effect rings)",
      'feature.radiation': "Radiation map (Safecast)",
      'feature.dartCoupling': "DART tsunami coupling",
      'feature.waterTwin': "Water twin \u2014 reservoirs & rivers",
      'feature.watchReplay': "Watch queries + day replay",
      'feature.quakeImpact': "Quake impact \u2014 felt & shaking",
      'feature.ripestat': "Routing pulse (RIPEstat)",
      'feature.ripestat.collector': "RIS collector",
      'feature.ripestat.originAs': "Origin AS",
      'feature.feodo': "Botnet C2 map (Feodo)",
      'feature.feodo.online': "C2 currently online",
      'feature.feodo.offline': "Historical / offline listings",
      'feature.gdelt': "Planetary attention (GDELT)",
      'feature.gdelt.positive': "Positive tone",
      'feature.gdelt.neutral': "Neutral tone",
      'feature.gdelt.negative': "Negative tone",
      'feature.meteors': "Night-side meteors (GMN)",
      'feature.meteors.velocity': "Entry velocity",
      'feature.meteors.mass': "Estimated mass",
      'feature.eibi': "Shortwave on air (EiBi)",
      'feature.eibi.onAir': "on air now",
      'feature.eibi.site': "Transmitter site code",
      'feature.aishub': "AIS receiver mesh (AISHub)",
      'feature.aishub.live': "Heard within the hour",
      'feature.aishub.day': "Heard today",
      'feature.aishub.stale': "Silent over a day",
      'feature.fireballs': "Fireball impacts",
      'feature.conjunctions': "Conjunction theater",
      'feature.reentry': "Reentry watch",
      'feature.cosmicRay': "Cosmic-ray weather",
      'feature.wxstations': "Station telemetry",
      'feature.time': "Time standard",
},
  },
  {
    id: 'nerv',
    name: 'NERV',
    tagline: 'Internal security terminal. Pattern classification in effect.',
    vars: {
      bg: '#0a0500',
      panel: '#140b00',
      accent: '#ff7a00',
      text: '#ffd9a8',
      warn: '#ffb300',
      ok: '#8bc34a',
      danger: '#ff2200',
      info: '#ffab40',
      fontUi: CONDENSED,
      fontMono: MONO,
    },
    effects: ['scanlines', 'vignette'],
    chrome:
      'Orange-on-black terminal blocks, severity banners, pattern-class stamps.',
    strings: {
      'app.title': 'TACTICAL TERMINAL',
      'app.tagline': 'Pattern classification in effect',
      'layer.firms': 'Thermal pattern (FIRMS)',
      'layer.earthquakes': 'Seismic pattern (USGS)',
      'layer.flights': 'Aerial pattern (ADS-B)',
      'layer.vessels': 'Surface pattern (AIS)',
      'layer.satellites': 'Orbital pattern (TLE)',
      'layer.weather': 'Atmospheric pattern (GIBS)',
      'layer.cyclones': 'Cyclone pattern',
      'layer.volcanoes': 'Eruption pattern',
      'layer.aurora': 'Ionospheric pattern',
      'layer.lightning': 'Discharge pattern',
      'layer.smoke': 'Plume pattern (HMS)',
      'layer.radar': 'Precipitation pattern (RainViewer)',
      'feature.events': 'Pattern log',
      'feature.dvr': 'Pattern archive',
      'feature.seismic': 'Wavefront analysis',
      'feature.lightning': 'Discharge pattern map',
      'feature.ovation': 'Ionospheric pattern forecast',
      'feature.skyAnomaly': 'Unclassified patterns',
      'feature.nlq': 'Query the terminal',
      'feature.sonification': 'Pattern audio',
      'feature.forecastFireSpread': 'Thermal pattern projection',
      'feature.forecastHurricaneCones': 'Cyclone pattern projection',
      'feature.forecastAsh': 'Ejecta pattern projection',
      'feature.notebook': 'Operations log',
      'feature.indoorTwin': 'Facility schematic',
      'feature.autoBriefing': 'Situation report',
      'severity.low': 'Pattern: blue',
      'severity.moderate': 'Pattern: yellow',
      'severity.high': 'Pattern: orange',
      'severity.critical': 'Pattern: red',
      'incident.label': 'Pattern event',
      'alert.label': 'Warning',
          'feature.akashic': "Planetary memory",
      'ui.akashic.open': "\u25c8 records",
      'ui.akashic.replayDay': "\u25b6 replay the day",
      'ui.akashic.viewInDvr': "view in GIBS DVR",
      'ui.akashic.noDays': "no archived days yet",
      'feature.webxr': "Inside the planet",
      'ui.webxr.enter': "\u25c9 step inside the planet (v1)",
      'ui.webxr.fallbackTitle': "\u25c8 inside the planet \u2014 360 viewer",
      'ui.webxr.fallbackNote': "(non-XR fallback; drag to look around)",
      'feature.gaiaVoice': "Planetary voice",
      'ui.gaia.listening': "\ud83d\udd0a gaia listening",
      'ui.gaia.muted': "\ud83d\udd07 gaia muted",
      'ui.gaia.test': "test voice",
      'feature.sharedEye': "Shared view",
      'ui.sharedEye.open': "\u25c8 shared eye",
      'ui.sharedEye.create': "create session",
      'ui.sharedEye.join': "join session",
      'ui.sharedEye.followMode': "follow-mode (no P2P needed)",
      'feature.interplanetary': "Interplanetary",
      'feature.planetaryDefense': "Planetary defense",
      'feature.eyesOn': "Eyes-on countdown",
      'feature.gravWaves': "Spacetime ripples",
      'feature.nwisGauges': "River gauges (USGS)",
      'feature.nwps': "Flood-wave forecast (NWM)",
      'feature.airQuality': "Air-quality haze (citizen sensors)",
      'feature.spaceWeather': "Space weather (Kp)",
      'feature.donki': "Solar storms (DONKI)",
      'feature.cableThreat': "Cable-threat correlation",
      'feature.nwsAlerts': "NWS alert polygons",
      'feature.sigmets': "Aviation SIGMETs",
      'feature.asteroids': "Asteroid flybys",
      'feature.biosphere': "Biosphere ticker",
      'feature.carbon': "Grid carbon intensity",
      'feature.certs': "Certificate transparency",
      'feature.civic': "Civic ticker",
      'feature.co2': "CO₂ (Mauna Loa)",
      'feature.felt': "Felt earthquakes (EMSC)",
      'feature.hazards': "Multi-hazard events (GDACS)",
      'feature.markets': "Markets (FX · BTC)",
      'feature.pota': "Who's on the air (POTA)",
      'feature.quakes': "Global quakes (5-catalog)",
      'feature.radioRef': "Radio reference",
      'feature.research': "Research ticker",
      'feature.satnogs': "Ground stations (SatNOGS)",
      'feature.uv': "UV index",
      'feature.volcano': "Volcano alerts (GeoNet + AVO)",
      'feature.terminatorRush': "Terminator Rush",
      'feature.deepTime': "Deep time (paleogeography)",
      'feature.oceanTwin': "Ocean twin (currents \u00b7 cables \u00b7 Argo)",
      'feature.whatIf': "What-if simulator (effect rings)",
      'feature.radiation': "Radiation map (Safecast)",
      'feature.dartCoupling': "DART tsunami coupling",
      'feature.waterTwin': "Water twin \u2014 reservoirs & rivers",
      'feature.watchReplay': "Watch queries + day replay",
      'feature.quakeImpact': "Quake impact \u2014 felt & shaking",
      'feature.ripestat': "Routing pulse (RIPEstat)",
      'feature.ripestat.collector': "RIS collector",
      'feature.ripestat.originAs': "Origin AS",
      'feature.feodo': "Botnet C2 map (Feodo)",
      'feature.feodo.online': "C2 currently online",
      'feature.feodo.offline': "Historical / offline listings",
      'feature.gdelt': "Planetary attention (GDELT)",
      'feature.gdelt.positive': "Positive tone",
      'feature.gdelt.neutral': "Neutral tone",
      'feature.gdelt.negative': "Negative tone",
      'feature.meteors': "Night-side meteors (GMN)",
      'feature.meteors.velocity': "Entry velocity",
      'feature.meteors.mass': "Estimated mass",
      'feature.eibi': "Shortwave on air (EiBi)",
      'feature.eibi.onAir': "on air now",
      'feature.eibi.site': "Transmitter site code",
      'feature.aishub': "AIS receiver mesh (AISHub)",
      'feature.aishub.live': "Heard within the hour",
      'feature.aishub.day': "Heard today",
      'feature.aishub.stale': "Silent over a day",
      'feature.fireballs': "Fireball impacts",
      'feature.conjunctions': "Conjunction theater",
      'feature.reentry': "Reentry watch",
      'feature.cosmicRay': "Cosmic-ray weather",
      'feature.wxstations': "Station pattern",
      'feature.time': "Time pattern",
},
  },
  {
    id: 'nightcity',
    name: 'Night City',
    tagline:
      'Wake up, samurai — the sprawl never sleeps and neither does the data.',
    vars: {
      bg: '#0b0014',
      panel: '#150826',
      accent: '#ff2fb3',
      text: '#e8f6ff',
      warn: '#ffea00',
      ok: '#00f0ff',
      danger: '#ff003c',
      info: '#00f0ff',
      fontUi: CONDENSED,
      fontMono: MONO,
    },
    effects: ['glitch', 'scanlines', 'noise'],
    chrome: 'Neon-bordered cards, chrome dividers, flickering signage headers.',
    strings: {
      'app.title': 'SPRAWL WATCH',
      'app.tagline': 'Wake up, samurai — the data never sleeps',
      'layer.firms': 'Burn zones (FIRMS)',
      'layer.earthquakes': 'Ground shakes (USGS)',
      'layer.flights': 'Sky traffic (ADS-B)',
      'layer.vessels': 'Harbor runners (AIS)',
      'layer.satellites': 'Orbitals (TLE)',
      'layer.weather': 'Atmo (GIBS)',
      'layer.cyclones': 'Mega-storms',
      'layer.volcanoes': 'Lava moods',
      'layer.aurora': 'Sky neon',
      'layer.lightning': 'Static storms',
      'layer.smoke': 'Smog (HMS)',
      'layer.radar': 'Rain scan (RainViewer)',
      'feature.events': 'The wire',
      'feature.dvr': 'Braindance replay',
      'feature.seismic': 'Shock ripples',
      'feature.lightning': 'Static grid',
      'feature.ovation': 'Sky-neon forecast',
      'feature.skyAnomaly': 'Weird chrome',
      'feature.nlq': 'Ask the net',
      'feature.sonification': 'Street audio',
      'feature.forecastFireSpread': 'Burn-zone projection',
      'feature.forecastHurricaneCones': 'Storm cones',
      'feature.forecastAsh': 'Ashfall forecast',
      'feature.notebook': 'Shard notes',
      'feature.indoorTwin': 'Interior gig',
      'feature.autoBriefing': 'Morning fix',
      'severity.low': 'Preem',
      'severity.moderate': 'Sketchy',
      'severity.high': 'Nova-hot',
      'severity.critical': 'Flatline',
      'incident.label': 'Gig',
      'alert.label': 'Ping',
          'feature.akashic': "Planetary memory",
      'ui.akashic.open': "\u25c8 records",
      'ui.akashic.replayDay': "\u25b6 replay the day",
      'ui.akashic.viewInDvr': "view in GIBS DVR",
      'ui.akashic.noDays': "no archived days yet",
      'feature.webxr': "Inside the planet",
      'ui.webxr.enter': "\u25c9 step inside the planet (v1)",
      'ui.webxr.fallbackTitle': "\u25c8 inside the planet \u2014 360 viewer",
      'ui.webxr.fallbackNote': "(non-XR fallback; drag to look around)",
      'feature.gaiaVoice': "Planetary voice",
      'ui.gaia.listening': "\ud83d\udd0a gaia listening",
      'ui.gaia.muted': "\ud83d\udd07 gaia muted",
      'ui.gaia.test': "test voice",
      'feature.sharedEye': "Shared view",
      'ui.sharedEye.open': "\u25c8 shared eye",
      'ui.sharedEye.create': "create session",
      'ui.sharedEye.join': "join session",
      'ui.sharedEye.followMode': "follow-mode (no P2P needed)",
      'feature.interplanetary': "Interplanetary",
      'feature.planetaryDefense': "Planetary defense",
      'feature.eyesOn': "Eyes-on countdown",
      'feature.gravWaves': "Spacetime ripples",
      'feature.nwisGauges': "River gauges (USGS)",
      'feature.nwps': "Flood-wave forecast (NWM)",
      'feature.airQuality': "Air-quality haze (citizen sensors)",
      'feature.spaceWeather': "Space weather (Kp)",
      'feature.donki': "Solar storms (DONKI)",
      'feature.cableThreat': "Cable-threat correlation",
      'feature.nwsAlerts': "NWS alert polygons",
      'feature.sigmets': "Aviation SIGMETs",
      'feature.asteroids': "Asteroid flybys",
      'feature.biosphere': "Biosphere ticker",
      'feature.carbon': "Grid carbon intensity",
      'feature.certs': "Certificate transparency",
      'feature.civic': "Civic ticker",
      'feature.co2': "CO₂ (Mauna Loa)",
      'feature.felt': "Felt earthquakes (EMSC)",
      'feature.hazards': "Multi-hazard events (GDACS)",
      'feature.markets': "Markets (FX · BTC)",
      'feature.pota': "Who's on the air (POTA)",
      'feature.quakes': "Global quakes (5-catalog)",
      'feature.radioRef': "Radio reference",
      'feature.research': "Research ticker",
      'feature.satnogs': "Ground stations (SatNOGS)",
      'feature.uv': "UV index",
      'feature.volcano': "Volcano alerts (GeoNet + AVO)",
      'feature.terminatorRush': "Terminator Rush",
      'feature.deepTime': "Deep time (paleogeography)",
      'feature.oceanTwin': "Ocean twin (currents \u00b7 cables \u00b7 Argo)",
      'feature.whatIf': "What-if simulator (effect rings)",
      'feature.radiation': "Radiation map (Safecast)",
      'feature.dartCoupling': "DART tsunami coupling",
      'feature.waterTwin': "Water twin \u2014 reservoirs & rivers",
      'feature.watchReplay': "Watch queries + day replay",
      'feature.quakeImpact': "Quake impact \u2014 felt & shaking",
      'feature.ripestat': "Routing pulse (RIPEstat)",
      'feature.ripestat.collector': "RIS collector",
      'feature.ripestat.originAs': "Origin AS",
      'feature.feodo': "Botnet C2 map (Feodo)",
      'feature.feodo.online': "C2 currently online",
      'feature.feodo.offline': "Historical / offline listings",
      'feature.gdelt': "Planetary attention (GDELT)",
      'feature.gdelt.positive': "Positive tone",
      'feature.gdelt.neutral': "Neutral tone",
      'feature.gdelt.negative': "Negative tone",
      'feature.meteors': "Night-side meteors (GMN)",
      'feature.meteors.velocity': "Entry velocity",
      'feature.meteors.mass': "Estimated mass",
      'feature.eibi': "Shortwave on air (EiBi)",
      'feature.eibi.onAir': "on air now",
      'feature.eibi.site': "Transmitter site code",
      'feature.aishub': "AIS receiver mesh (AISHub)",
      'feature.aishub.live': "Heard within the hour",
      'feature.aishub.day': "Heard today",
      'feature.aishub.stale': "Silent over a day",
      'feature.fireballs': "Fireball impacts",
      'feature.conjunctions': "Conjunction theater",
      'feature.reentry': "Reentry watch",
      'feature.cosmicRay': "Cosmic-ray weather",
      'feature.wxstations': "Station feed",
      'feature.time': "Time feed",
},
  },
  {
    id: 'apollo',
    name: 'Apollo Mission Control',
    tagline: 'Flight, this is Globe. All controllers, report GO/NO-GO.',
    vars: {
      bg: '#000000',
      panel: '#0a0f0a',
      accent: '#33ff33',
      text: '#c8ffc8',
      warn: '#ffff00',
      ok: '#33ff33',
      danger: '#ff3333',
      info: '#66ffcc',
      fontUi: CONDENSED,
      fontMono: MONO,
    },
    effects: ['scanlines', 'phosphorGlow'],
    chrome:
      'Console-row cards with call-sign labels, GO/NO-GO status lamps, mission-clock headers.',
    strings: {
      'app.title': 'GLOBE CONTROL',
      'app.tagline': 'Flight, this is Globe — report GO/NO-GO',
      'layer.firms': 'Fire events (FIRMS)',
      'layer.earthquakes': 'Seismic events (USGS)',
      'layer.flights': 'Air traffic (ADS-B)',
      'layer.vessels': 'Recovery fleet (AIS)',
      'layer.satellites': 'Tracking network (TLE)',
      'layer.weather': 'Weather (GIBS)',
      'layer.cyclones': 'Tropical systems',
      'layer.volcanoes': 'Volcanic events',
      'layer.aurora': 'Aurora',
      'layer.lightning': 'Lightning',
      'layer.smoke': 'Smoke (HMS)',
      'layer.radar': 'Radar (RainViewer)',
      'feature.events': 'Event log',
      'feature.dvr': 'Mission replay',
      'feature.seismic': 'Wavefront tracking',
      'feature.lightning': 'Lightning display',
      'feature.ovation': 'Aurora forecast',
      'feature.skyAnomaly': 'Anomaly reports',
      'feature.nlq': 'Ask Flight',
      'feature.sonification': 'Telemetry audio',
      'feature.forecastFireSpread': 'Fire trajectory',
      'feature.forecastHurricaneCones': 'Storm cones',
      'feature.forecastAsh': 'Ash trajectory',
      'feature.notebook': 'Flight log',
      'feature.indoorTwin': 'Cabin schematic',
      'feature.autoBriefing': 'Shift handover',
      'severity.low': 'GO',
      'severity.moderate': 'GO with caution',
      'severity.high': 'NO-GO',
      'severity.critical': 'ABORT',
      'incident.label': 'Anomaly',
      'alert.label': 'Caution',
          'feature.akashic': "Planetary memory",
      'ui.akashic.open': "\u25c8 records",
      'ui.akashic.replayDay': "\u25b6 replay the day",
      'ui.akashic.viewInDvr': "view in GIBS DVR",
      'ui.akashic.noDays': "no archived days yet",
      'feature.webxr': "Inside the planet",
      'ui.webxr.enter': "\u25c9 step inside the planet (v1)",
      'ui.webxr.fallbackTitle': "\u25c8 inside the planet \u2014 360 viewer",
      'ui.webxr.fallbackNote': "(non-XR fallback; drag to look around)",
      'feature.gaiaVoice': "Planetary voice",
      'ui.gaia.listening': "\ud83d\udd0a gaia listening",
      'ui.gaia.muted': "\ud83d\udd07 gaia muted",
      'ui.gaia.test': "test voice",
      'feature.sharedEye': "Shared view",
      'ui.sharedEye.open': "\u25c8 shared eye",
      'ui.sharedEye.create': "create session",
      'ui.sharedEye.join': "join session",
      'ui.sharedEye.followMode': "follow-mode (no P2P needed)",
      'feature.interplanetary': "Interplanetary",
      'feature.planetaryDefense': "Planetary defense",
      'feature.eyesOn': "Eyes-on countdown",
      'feature.gravWaves': "Spacetime ripples",
      'feature.nwisGauges': "River gauges (USGS)",
      'feature.nwps': "Flood-wave forecast (NWM)",
      'feature.airQuality': "Air-quality haze (citizen sensors)",
      'feature.spaceWeather': "Space weather (Kp)",
      'feature.donki': "Solar storms (DONKI)",
      'feature.cableThreat': "Cable-threat correlation",
      'feature.nwsAlerts': "NWS alert polygons",
      'feature.sigmets': "Aviation SIGMETs",
      'feature.asteroids': "Asteroid flybys",
      'feature.biosphere': "Biosphere ticker",
      'feature.carbon': "Grid carbon intensity",
      'feature.certs': "Certificate transparency",
      'feature.civic': "Civic ticker",
      'feature.co2': "CO₂ (Mauna Loa)",
      'feature.felt': "Felt earthquakes (EMSC)",
      'feature.hazards': "Multi-hazard events (GDACS)",
      'feature.markets': "Markets (FX · BTC)",
      'feature.pota': "Who's on the air (POTA)",
      'feature.quakes': "Global quakes (5-catalog)",
      'feature.radioRef': "Radio reference",
      'feature.research': "Research ticker",
      'feature.satnogs': "Ground stations (SatNOGS)",
      'feature.uv': "UV index",
      'feature.volcano': "Volcano alerts (GeoNet + AVO)",
      'feature.terminatorRush': "Terminator Rush",
      'feature.deepTime': "Deep time (paleogeography)",
      'feature.oceanTwin': "Ocean twin (currents \u00b7 cables \u00b7 Argo)",
      'feature.whatIf': "What-if simulator (effect rings)",
      'feature.radiation': "Radiation map (Safecast)",
      'feature.dartCoupling': "DART tsunami coupling",
      'feature.waterTwin': "Water twin \u2014 reservoirs & rivers",
      'feature.watchReplay': "Watch queries + day replay",
      'feature.quakeImpact': "Quake impact \u2014 felt & shaking",
      'feature.ripestat': "Routing pulse (RIPEstat)",
      'feature.ripestat.collector': "RIS collector",
      'feature.ripestat.originAs': "Origin AS",
      'feature.feodo': "Botnet C2 map (Feodo)",
      'feature.feodo.online': "C2 currently online",
      'feature.feodo.offline': "Historical / offline listings",
      'feature.gdelt': "Planetary attention (GDELT)",
      'feature.gdelt.positive': "Positive tone",
      'feature.gdelt.neutral': "Neutral tone",
      'feature.gdelt.negative': "Negative tone",
      'feature.meteors': "Night-side meteors (GMN)",
      'feature.meteors.velocity': "Entry velocity",
      'feature.meteors.mass': "Estimated mass",
      'feature.eibi': "Shortwave on air (EiBi)",
      'feature.eibi.onAir': "on air now",
      'feature.eibi.site': "Transmitter site code",
      'feature.aishub': "AIS receiver mesh (AISHub)",
      'feature.aishub.live': "Heard within the hour",
      'feature.aishub.day': "Heard today",
      'feature.aishub.stale': "Silent over a day",
      'feature.fireballs': "Fireball impacts",
      'feature.conjunctions': "Conjunction theater",
      'feature.reentry': "Reentry watch",
      'feature.cosmicRay': "Cosmic-ray weather",
      'feature.wxstations': "Station watch",
      'feature.time': "Mission clock ref",
},
  },
  {
    id: 'weyland',
    name: 'Weyland-Yutani',
    tagline:
      'Building better worlds. All occurrences logged for shareholder review.',
    vars: {
      bg: '#0d0a04',
      panel: '#171106',
      accent: '#ffb000',
      text: '#ffe9b8',
      warn: '#ffcf40',
      ok: '#b8e986',
      danger: '#ff5a36',
      info: '#ffd27a',
      fontUi: UI_SANS,
      fontMono: MONO,
    },
    effects: ['scanlines', 'vignette', 'phosphorGlow'],
    chrome:
      'Amber CRT forms, corporate memo headers, fine-print disclaimers on every card.',
    strings: {
      'app.title': 'CORPORATE SURVEY TERMINAL',
      'app.tagline': 'Building better worlds — all occurrences logged',
      'layer.firms': 'Thermal asset events (FIRMS)',
      'layer.earthquakes': 'Subsurface restructuring (USGS)',
      'layer.flights': 'Aerial logistics (ADS-B)',
      'layer.vessels': 'Maritime logistics (AIS)',
      'layer.satellites': 'Orbital assets (TLE)',
      'layer.weather': 'Atmospheric conditions (GIBS)',
      'layer.cyclones': 'Weather restructuring',
      'layer.volcanoes': 'Geothermal venting',
      'layer.aurora': 'Atmospheric luminescence',
      'layer.lightning': 'Electrical discharging',
      'layer.smoke': 'Airborne particulates (HMS)',
      'layer.radar': 'Precipitation overview (RainViewer)',
      'feature.events': 'Occurrence digest',
      'feature.dvr': 'Historical review',
      'feature.seismic': 'Subsurface wave analysis',
      'feature.lightning': 'Discharge overview',
      'feature.ovation': 'Luminescence forecast',
      'feature.skyAnomaly': 'Unscheduled phenomena',
      'feature.nlq': 'Submit inquiry',
      'feature.sonification': 'Acoustic summary',
      'feature.forecastFireSpread': 'Thermal expansion outlook',
      'feature.forecastHurricaneCones': 'Weather restructuring outlook',
      'feature.forecastAsh': 'Particulate outlook',
      'feature.notebook': 'Memoranda',
      'feature.indoorTwin': 'Facility overview',
      'feature.autoBriefing': 'Executive summary',
      'severity.low': 'Within tolerance',
      'severity.moderate': 'Notable variance',
      'severity.high': 'Material variance',
      'severity.critical': 'Acceptable loss parameters exceeded',
      'incident.label': 'Occurrence',
      'alert.label': 'Memorandum',
          'feature.akashic': "Planetary memory",
      'ui.akashic.open': "\u25c8 records",
      'ui.akashic.replayDay': "\u25b6 replay the day",
      'ui.akashic.viewInDvr': "view in GIBS DVR",
      'ui.akashic.noDays': "no archived days yet",
      'feature.webxr': "Inside the planet",
      'ui.webxr.enter': "\u25c9 step inside the planet (v1)",
      'ui.webxr.fallbackTitle': "\u25c8 inside the planet \u2014 360 viewer",
      'ui.webxr.fallbackNote': "(non-XR fallback; drag to look around)",
      'feature.gaiaVoice': "Planetary voice",
      'ui.gaia.listening': "\ud83d\udd0a gaia listening",
      'ui.gaia.muted': "\ud83d\udd07 gaia muted",
      'ui.gaia.test': "test voice",
      'feature.sharedEye': "Shared view",
      'ui.sharedEye.open': "\u25c8 shared eye",
      'ui.sharedEye.create': "create session",
      'ui.sharedEye.join': "join session",
      'ui.sharedEye.followMode': "follow-mode (no P2P needed)",
      'feature.interplanetary': "Interplanetary",
      'feature.planetaryDefense': "Planetary defense",
      'feature.eyesOn': "Eyes-on countdown",
      'feature.gravWaves': "Spacetime ripples",
      'feature.nwisGauges': "River gauges (USGS)",
      'feature.nwps': "Flood-wave forecast (NWM)",
      'feature.airQuality': "Air-quality haze (citizen sensors)",
      'feature.spaceWeather': "Space weather (Kp)",
      'feature.donki': "Solar storms (DONKI)",
      'feature.cableThreat': "Cable-threat correlation",
      'feature.nwsAlerts': "NWS alert polygons",
      'feature.sigmets': "Aviation SIGMETs",
      'feature.asteroids': "Asteroid flybys",
      'feature.biosphere': "Biosphere ticker",
      'feature.carbon': "Grid carbon intensity",
      'feature.certs': "Certificate transparency",
      'feature.civic': "Civic ticker",
      'feature.co2': "CO₂ (Mauna Loa)",
      'feature.felt': "Felt earthquakes (EMSC)",
      'feature.hazards': "Multi-hazard events (GDACS)",
      'feature.markets': "Markets (FX · BTC)",
      'feature.pota': "Who's on the air (POTA)",
      'feature.quakes': "Global quakes (5-catalog)",
      'feature.radioRef': "Radio reference",
      'feature.research': "Research ticker",
      'feature.satnogs': "Ground stations (SatNOGS)",
      'feature.uv': "UV index",
      'feature.volcano': "Volcano alerts (GeoNet + AVO)",
      'feature.terminatorRush': "Terminator Rush",
      'feature.deepTime': "Deep time (paleogeography)",
      'feature.oceanTwin': "Ocean twin (currents \u00b7 cables \u00b7 Argo)",
      'feature.whatIf': "What-if simulator (effect rings)",
      'feature.radiation': "Radiation map (Safecast)",
      'feature.dartCoupling': "DART tsunami coupling",
      'feature.waterTwin': "Water twin \u2014 reservoirs & rivers",
      'feature.watchReplay': "Watch queries + day replay",
      'feature.quakeImpact': "Quake impact \u2014 felt & shaking",
      'feature.ripestat': "Routing pulse (RIPEstat)",
      'feature.ripestat.collector': "RIS collector",
      'feature.ripestat.originAs': "Origin AS",
      'feature.feodo': "Botnet C2 map (Feodo)",
      'feature.feodo.online': "C2 currently online",
      'feature.feodo.offline': "Historical / offline listings",
      'feature.gdelt': "Planetary attention (GDELT)",
      'feature.gdelt.positive': "Positive tone",
      'feature.gdelt.neutral': "Neutral tone",
      'feature.gdelt.negative': "Negative tone",
      'feature.meteors': "Night-side meteors (GMN)",
      'feature.meteors.velocity': "Entry velocity",
      'feature.meteors.mass': "Estimated mass",
      'feature.eibi': "Shortwave on air (EiBi)",
      'feature.eibi.onAir': "on air now",
      'feature.eibi.site': "Transmitter site code",
      'feature.aishub': "AIS receiver mesh (AISHub)",
      'feature.aishub.live': "Heard within the hour",
      'feature.aishub.day': "Heard today",
      'feature.aishub.stale': "Silent over a day",
      'feature.fireballs': "Fireball impacts",
      'feature.conjunctions': "Conjunction theater",
      'feature.reentry': "Reentry watch",
      'feature.cosmicRay': "Cosmic-ray weather",
      'feature.wxstations': "Station log",
      'feature.time': "Chronology log",
},
  },
  {
    id: 'synthwave',
    name: 'Synthwave 80s',
    tagline: 'Cruising the grid at midnight. The future is neon.',
    vars: {
      bg: '#0d0221',
      panel: '#1a0b2e',
      accent: '#ff71ce',
      text: '#f9f7ff',
      warn: '#fffb96',
      ok: '#01cdfe',
      danger: '#ff3860',
      info: '#01cdfe',
      fontUi: CONDENSED,
      fontMono: MONO,
    },
    effects: ['vignette', 'scanlines'],
    chrome:
      'Chrome-gradient headers, neon grid dividers, sunset-gradient accents.',
    strings: {
      'app.title': 'MIDNIGHT GRID',
      'app.tagline': 'Cruising the grid — the future is neon',
      'layer.firms': 'Fire zones (FIRMS)',
      'layer.earthquakes': 'Quakes (USGS)',
      'layer.flights': 'Sky cruisers (ADS-B)',
      'layer.vessels': 'Sea cruisers (AIS)',
      'layer.satellites': 'Star riders (TLE)',
      'layer.weather': 'Atmosphere (GIBS)',
      'layer.cyclones': 'Storm riders',
      'layer.volcanoes': 'Lava lights',
      'layer.aurora': 'Neon skies',
      'layer.lightning': 'Electric storms',
      'layer.smoke': 'Haze (HMS)',
      'layer.radar': 'Rain waves (RainViewer)',
      'feature.events': 'Night wire',
      'feature.dvr': 'Rewind cassette',
      'feature.seismic': 'Bass waves',
      'feature.lightning': 'Electric grid',
      'feature.ovation': 'Neon-sky forecast',
      'feature.skyAnomaly': 'Glitch sightings',
      'feature.nlq': 'Ask the DJ',
      'feature.sonification': 'Synth mode',
      'feature.forecastFireSpread': 'Fire forecast',
      'feature.forecastHurricaneCones': 'Storm cones',
      'feature.forecastAsh': 'Ash forecast',
      'feature.notebook': 'Mixtape notes',
      'feature.indoorTwin': 'Arcade interior',
      'feature.autoBriefing': 'Morning drive-time',
      'severity.low': 'Chill',
      'severity.moderate': 'Heating up',
      'severity.high': 'Radical',
      'severity.critical': 'Total meltdown',
      'incident.label': 'Event',
      'alert.label': 'Shout-out',
          'feature.akashic': "Planetary memory",
      'ui.akashic.open': "\u25c8 records",
      'ui.akashic.replayDay': "\u25b6 replay the day",
      'ui.akashic.viewInDvr': "view in GIBS DVR",
      'ui.akashic.noDays': "no archived days yet",
      'feature.webxr': "Inside the planet",
      'ui.webxr.enter': "\u25c9 step inside the planet (v1)",
      'ui.webxr.fallbackTitle': "\u25c8 inside the planet \u2014 360 viewer",
      'ui.webxr.fallbackNote': "(non-XR fallback; drag to look around)",
      'feature.gaiaVoice': "Planetary voice",
      'ui.gaia.listening': "\ud83d\udd0a gaia listening",
      'ui.gaia.muted': "\ud83d\udd07 gaia muted",
      'ui.gaia.test': "test voice",
      'feature.sharedEye': "Shared view",
      'ui.sharedEye.open': "\u25c8 shared eye",
      'ui.sharedEye.create': "create session",
      'ui.sharedEye.join': "join session",
      'ui.sharedEye.followMode': "follow-mode (no P2P needed)",
      'feature.interplanetary': "Interplanetary",
      'feature.planetaryDefense': "Planetary defense",
      'feature.eyesOn': "Eyes-on countdown",
      'feature.gravWaves': "Spacetime ripples",
      'feature.nwisGauges': "River gauges (USGS)",
      'feature.nwps': "Flood-wave forecast (NWM)",
      'feature.airQuality': "Air-quality haze (citizen sensors)",
      'feature.spaceWeather': "Space weather (Kp)",
      'feature.donki': "Solar storms (DONKI)",
      'feature.cableThreat': "Cable-threat correlation",
      'feature.nwsAlerts': "NWS alert polygons",
      'feature.sigmets': "Aviation SIGMETs",
      'feature.asteroids': "Asteroid flybys",
      'feature.biosphere': "Biosphere ticker",
      'feature.carbon': "Grid carbon intensity",
      'feature.certs': "Certificate transparency",
      'feature.civic': "Civic ticker",
      'feature.co2': "CO₂ (Mauna Loa)",
      'feature.felt': "Felt earthquakes (EMSC)",
      'feature.hazards': "Multi-hazard events (GDACS)",
      'feature.markets': "Markets (FX · BTC)",
      'feature.pota': "Who's on the air (POTA)",
      'feature.quakes': "Global quakes (5-catalog)",
      'feature.radioRef': "Radio reference",
      'feature.research': "Research ticker",
      'feature.satnogs': "Ground stations (SatNOGS)",
      'feature.uv': "UV index",
      'feature.volcano': "Volcano alerts (GeoNet + AVO)",
      'feature.terminatorRush': "Terminator Rush",
      'feature.deepTime': "Deep time (paleogeography)",
      'feature.oceanTwin': "Ocean twin (currents \u00b7 cables \u00b7 Argo)",
      'feature.whatIf': "What-if simulator (effect rings)",
      'feature.radiation': "Radiation map (Safecast)",
      'feature.dartCoupling': "DART tsunami coupling",
      'feature.waterTwin': "Water twin \u2014 reservoirs & rivers",
      'feature.watchReplay': "Watch queries + day replay",
      'feature.quakeImpact': "Quake impact \u2014 felt & shaking",
      'feature.ripestat': "Routing pulse (RIPEstat)",
      'feature.ripestat.collector': "RIS collector",
      'feature.ripestat.originAs': "Origin AS",
      'feature.feodo': "Botnet C2 map (Feodo)",
      'feature.feodo.online': "C2 currently online",
      'feature.feodo.offline': "Historical / offline listings",
      'feature.gdelt': "Planetary attention (GDELT)",
      'feature.gdelt.positive': "Positive tone",
      'feature.gdelt.neutral': "Neutral tone",
      'feature.gdelt.negative': "Negative tone",
      'feature.meteors': "Night-side meteors (GMN)",
      'feature.meteors.velocity': "Entry velocity",
      'feature.meteors.mass': "Estimated mass",
      'feature.eibi': "Shortwave on air (EiBi)",
      'feature.eibi.onAir': "on air now",
      'feature.eibi.site': "Transmitter site code",
      'feature.aishub': "AIS receiver mesh (AISHub)",
      'feature.aishub.live': "Heard within the hour",
      'feature.aishub.day': "Heard today",
      'feature.aishub.stale': "Silent over a day",
      'feature.fireballs': "Fireball impacts",
      'feature.conjunctions': "Conjunction theater",
      'feature.reentry': "Reentry watch",
      'feature.cosmicRay': "Cosmic-ray weather",
      'feature.wxstations': "Weather stations",
      'feature.time': "Time standards",
},
  },
  {
    id: 'scp',
    name: 'SCP Terminal',
    tagline: 'Secure. Contain. Protect. All items logged.',
    vars: {
      bg: '#0a0a0a',
      panel: '#121212',
      accent: '#c8c8c8',
      text: '#e0e0e0',
      warn: '#ffcc00',
      ok: '#66bb66',
      danger: '#cc0000',
      info: '#7aa2c8',
      fontUi: UI_SANS,
      fontMono: MONO,
    },
    effects: ['vignette'],
    chrome:
      'Clinical dossier cards, item-number stamps, redacted-field bars, containment-class seals.',
    strings: {
      'app.title': 'ANOMALY DATABASE',
      'app.tagline': 'Secure. Contain. Protect. All items logged.',
      'layer.firms': 'Thermal items (FIRMS)',
      'layer.earthquakes': 'Seismic items (USGS)',
      'layer.flights': 'Aerial items (ADS-B)',
      'layer.vessels': 'Maritime items (AIS)',
      'layer.satellites': 'Orbital items (TLE)',
      'layer.weather': 'Atmospheric items (GIBS)',
      'layer.cyclones': 'Cyclone-class items',
      'layer.volcanoes': 'Eruption-class items',
      'layer.aurora': 'Luminescent items',
      'layer.lightning': 'Discharge items',
      'layer.smoke': 'Particulate items (HMS)',
      'layer.radar': 'Precipitation items (RainViewer)',
      'feature.events': 'Item activity log',
      'feature.dvr': 'Historical item review',
      'feature.seismic': 'Wavefront documentation',
      'feature.lightning': 'Discharge item map',
      'feature.ovation': 'Luminescence forecast',
      'feature.skyAnomaly': 'Uncontained items',
      'feature.nlq': 'Query the database',
      'feature.sonification': 'Acoustic documentation',
      'feature.forecastFireSpread': 'Thermal spread projection',
      'feature.forecastHurricaneCones': 'Cyclone track projection',
      'feature.forecastAsh': 'Ejecta projection',
      'feature.notebook': 'Researcher notes',
      'feature.indoorTwin': 'Site schematic',
      'feature.autoBriefing': 'Daily containment summary',
      'severity.low': 'Class 1 — Safe',
      'severity.moderate': 'Class 2 — Euclid',
      'severity.high': 'Class 3 — Keter',
      'severity.critical': 'Class 4 — Breach',
      'incident.label': 'Item',
      'alert.label': 'Addendum',
          'feature.akashic': "Planetary memory",
      'ui.akashic.open': "\u25c8 records",
      'ui.akashic.replayDay': "\u25b6 replay the day",
      'ui.akashic.viewInDvr': "view in GIBS DVR",
      'ui.akashic.noDays': "no archived days yet",
      'feature.webxr': "Inside the planet",
      'ui.webxr.enter': "\u25c9 step inside the planet (v1)",
      'ui.webxr.fallbackTitle': "\u25c8 inside the planet \u2014 360 viewer",
      'ui.webxr.fallbackNote': "(non-XR fallback; drag to look around)",
      'feature.gaiaVoice': "Planetary voice",
      'ui.gaia.listening': "\ud83d\udd0a gaia listening",
      'ui.gaia.muted': "\ud83d\udd07 gaia muted",
      'ui.gaia.test': "test voice",
      'feature.sharedEye': "Shared view",
      'ui.sharedEye.open': "\u25c8 shared eye",
      'ui.sharedEye.create': "create session",
      'ui.sharedEye.join': "join session",
      'ui.sharedEye.followMode': "follow-mode (no P2P needed)",
      'feature.interplanetary': "Interplanetary",
      'feature.planetaryDefense': "Planetary defense",
      'feature.eyesOn': "Eyes-on countdown",
      'feature.gravWaves': "Spacetime ripples",
      'feature.nwisGauges': "River gauges (USGS)",
      'feature.nwps': "Flood-wave forecast (NWM)",
      'feature.airQuality': "Air-quality haze (citizen sensors)",
      'feature.spaceWeather': "Space weather (Kp)",
      'feature.donki': "Solar storms (DONKI)",
      'feature.cableThreat': "Cable-threat correlation",
      'feature.nwsAlerts': "NWS alert polygons",
      'feature.sigmets': "Aviation SIGMETs",
      'feature.asteroids': "Asteroid flybys",
      'feature.biosphere': "Biosphere ticker",
      'feature.carbon': "Grid carbon intensity",
      'feature.certs': "Certificate transparency",
      'feature.civic': "Civic ticker",
      'feature.co2': "CO₂ (Mauna Loa)",
      'feature.felt': "Felt earthquakes (EMSC)",
      'feature.hazards': "Multi-hazard events (GDACS)",
      'feature.markets': "Markets (FX · BTC)",
      'feature.pota': "Who's on the air (POTA)",
      'feature.quakes': "Global quakes (5-catalog)",
      'feature.radioRef': "Radio reference",
      'feature.research': "Research ticker",
      'feature.satnogs': "Ground stations (SatNOGS)",
      'feature.uv': "UV index",
      'feature.volcano': "Volcano alerts (GeoNet + AVO)",
      'feature.terminatorRush': "Terminator Rush",
      'feature.deepTime': "Deep time (paleogeography)",
      'feature.oceanTwin': "Ocean twin (currents \u00b7 cables \u00b7 Argo)",
      'feature.whatIf': "What-if simulator (effect rings)",
      'feature.radiation': "Radiation map (Safecast)",
      'feature.dartCoupling': "DART tsunami coupling",
      'feature.waterTwin': "Water twin \u2014 reservoirs & rivers",
      'feature.watchReplay': "Watch queries + day replay",
      'feature.quakeImpact': "Quake impact \u2014 felt & shaking",
      'feature.ripestat': "Routing pulse (RIPEstat)",
      'feature.ripestat.collector': "RIS collector",
      'feature.ripestat.originAs': "Origin AS",
      'feature.feodo': "Botnet C2 map (Feodo)",
      'feature.feodo.online': "C2 currently online",
      'feature.feodo.offline': "Historical / offline listings",
      'feature.gdelt': "Planetary attention (GDELT)",
      'feature.gdelt.positive': "Positive tone",
      'feature.gdelt.neutral': "Neutral tone",
      'feature.gdelt.negative': "Negative tone",
      'feature.meteors': "Night-side meteors (GMN)",
      'feature.meteors.velocity': "Entry velocity",
      'feature.meteors.mass': "Estimated mass",
      'feature.eibi': "Shortwave on air (EiBi)",
      'feature.eibi.onAir': "on air now",
      'feature.eibi.site': "Transmitter site code",
      'feature.aishub': "AIS receiver mesh (AISHub)",
      'feature.aishub.live': "Heard within the hour",
      'feature.aishub.day': "Heard today",
      'feature.aishub.stale': "Silent over a day",
      'feature.fireballs': "Fireball impacts",
      'feature.conjunctions': "Conjunction theater",
      'feature.reentry': "Reentry watch",
      'feature.cosmicRay': "Cosmic-ray weather",
      'feature.wxstations': "Station file",
      'feature.time': "Temporal file",
},
  },
  {
    id: 'tron',
    name: 'Tron Grid',
    tagline: 'End of line. All programs report.',
    vars: {
      bg: '#000000',
      panel: '#05070d',
      accent: '#00c8ff',
      text: '#d6f4ff',
      warn: '#ffb000',
      ok: '#00ffa3',
      danger: '#ff5e00',
      info: '#00c8ff',
      fontUi: CONDENSED,
      fontMono: MONO,
    },
    effects: ['scanlines', 'phosphorGlow'],
    chrome:
      'Glowing blue circuit-line borders, minimal derezzed panels, identity-disc status rings.',
    strings: {
      'app.title': 'GRID TERMINAL',
      'app.tagline': 'End of line — all programs report',
      'layer.firms': 'Thermal programs (FIRMS)',
      'layer.earthquakes': 'Seismic faults (USGS)',
      'layer.flights': 'Air programs (ADS-B)',
      'layer.vessels': 'Sea programs (AIS)',
      'layer.satellites': 'Orbital programs (TLE)',
      'layer.weather': 'Atmosphere grid (GIBS)',
      'layer.cyclones': 'Storm cycles',
      'layer.volcanoes': 'Magma vents',
      'layer.aurora': 'Light ribbons',
      'layer.lightning': 'Energy discharges',
      'layer.smoke': 'Static haze (HMS)',
      'layer.radar': 'Rain grid (RainViewer)',
      'feature.events': 'Program log',
      'feature.dvr': 'Cycle rewind',
      'feature.seismic': 'Shock cycles',
      'feature.lightning': 'Discharge grid',
      'feature.ovation': 'Ribbon forecast',
      'feature.skyAnomaly': 'Rogue programs',
      'feature.nlq': 'Query the Grid',
      'feature.sonification': 'Audio cycles',
      'feature.forecastFireSpread': 'Thermal projection',
      'feature.forecastHurricaneCones': 'Storm-cycle projection',
      'feature.forecastAsh': 'Ash projection',
      'feature.notebook': 'Program notes',
      'feature.indoorTwin': 'Sector schematic',
      'feature.autoBriefing': 'Cycle briefing',
      'severity.low': 'Stable cycle',
      'severity.moderate': 'Degraded',
      'severity.high': 'Critical fault',
      'severity.critical': 'Derezzed',
      'incident.label': 'Fault',
      'alert.label': 'Ping',
          'feature.akashic': "Planetary memory",
      'ui.akashic.open': "\u25c8 records",
      'ui.akashic.replayDay': "\u25b6 replay the day",
      'ui.akashic.viewInDvr': "view in GIBS DVR",
      'ui.akashic.noDays': "no archived days yet",
      'feature.webxr': "Inside the planet",
      'ui.webxr.enter': "\u25c9 step inside the planet (v1)",
      'ui.webxr.fallbackTitle': "\u25c8 inside the planet \u2014 360 viewer",
      'ui.webxr.fallbackNote': "(non-XR fallback; drag to look around)",
      'feature.gaiaVoice': "Planetary voice",
      'ui.gaia.listening': "\ud83d\udd0a gaia listening",
      'ui.gaia.muted': "\ud83d\udd07 gaia muted",
      'ui.gaia.test': "test voice",
      'feature.sharedEye': "Shared view",
      'ui.sharedEye.open': "\u25c8 shared eye",
      'ui.sharedEye.create': "create session",
      'ui.sharedEye.join': "join session",
      'ui.sharedEye.followMode': "follow-mode (no P2P needed)",
      'feature.interplanetary': "Interplanetary",
      'feature.planetaryDefense': "Planetary defense",
      'feature.eyesOn': "Eyes-on countdown",
      'feature.gravWaves': "Spacetime ripples",
      'feature.nwisGauges': "River gauges (USGS)",
      'feature.nwps': "Flood-wave forecast (NWM)",
      'feature.airQuality': "Air-quality haze (citizen sensors)",
      'feature.spaceWeather': "Space weather (Kp)",
      'feature.donki': "Solar storms (DONKI)",
      'feature.cableThreat': "Cable-threat correlation",
      'feature.nwsAlerts': "NWS alert polygons",
      'feature.sigmets': "Aviation SIGMETs",
      'feature.asteroids': "Asteroid flybys",
      'feature.biosphere': "Biosphere ticker",
      'feature.carbon': "Grid carbon intensity",
      'feature.certs': "Certificate transparency",
      'feature.civic': "Civic ticker",
      'feature.co2': "CO₂ (Mauna Loa)",
      'feature.felt': "Felt earthquakes (EMSC)",
      'feature.hazards': "Multi-hazard events (GDACS)",
      'feature.markets': "Markets (FX · BTC)",
      'feature.pota': "Who's on the air (POTA)",
      'feature.quakes': "Global quakes (5-catalog)",
      'feature.radioRef': "Radio reference",
      'feature.research': "Research ticker",
      'feature.satnogs': "Ground stations (SatNOGS)",
      'feature.uv': "UV index",
      'feature.volcano': "Volcano alerts (GeoNet + AVO)",
      'feature.terminatorRush': "Terminator Rush",
      'feature.deepTime': "Deep time (paleogeography)",
      'feature.oceanTwin': "Ocean twin (currents \u00b7 cables \u00b7 Argo)",
      'feature.whatIf': "What-if simulator (effect rings)",
      'feature.radiation': "Radiation map (Safecast)",
      'feature.dartCoupling': "DART tsunami coupling",
      'feature.waterTwin': "Water twin \u2014 reservoirs & rivers",
      'feature.watchReplay': "Watch queries + day replay",
      'feature.quakeImpact': "Quake impact \u2014 felt & shaking",
      'feature.ripestat': "Routing pulse (RIPEstat)",
      'feature.ripestat.collector': "RIS collector",
      'feature.ripestat.originAs': "Origin AS",
      'feature.feodo': "Botnet C2 map (Feodo)",
      'feature.feodo.online': "C2 currently online",
      'feature.feodo.offline': "Historical / offline listings",
      'feature.gdelt': "Planetary attention (GDELT)",
      'feature.gdelt.positive': "Positive tone",
      'feature.gdelt.neutral': "Neutral tone",
      'feature.gdelt.negative': "Negative tone",
      'feature.meteors': "Night-side meteors (GMN)",
      'feature.meteors.velocity': "Entry velocity",
      'feature.meteors.mass': "Estimated mass",
      'feature.eibi': "Shortwave on air (EiBi)",
      'feature.eibi.onAir': "on air now",
      'feature.eibi.site': "Transmitter site code",
      'feature.aishub': "AIS receiver mesh (AISHub)",
      'feature.aishub.live': "Heard within the hour",
      'feature.aishub.day': "Heard today",
      'feature.aishub.stale': "Silent over a day",
      'feature.fireballs': "Fireball impacts",
      'feature.conjunctions': "Conjunction theater",
      'feature.reentry': "Reentry watch",
      'feature.cosmicRay': "Cosmic-ray weather",
      'feature.wxstations': "Station program",
      'feature.time': "Time program",
},
  },
];
