/**
 * Wave 10 — generic surge engine unit tests (hand-written; the per-spec
 * tests are auto-generated by scripts/surge-generate.mjs).
 */
import assert from 'node:assert/strict';
import test from 'node:test';
import {
  resolvePath,
  validateSpec,
  extractItems,
  applyMap,
  filterRequired,
  buildPayload,
  specProxy,
  numOrNull,
  _surgeInternals,
} from '../../server/providers/wave10/generic.js';

const goodSpec = () => ({
  id: 'test-widget',
  title: 'Test Widget Feed',
  url: 'https://example.invalid/widgets.json',
  ttlSeconds: 60,
  extract: {
    items: '$.data.widgets',
    limit: 10,
    map: {
      name: '$.label',
      code: '$.codes[0]',
      lat: '$.loc.lat',
      value: '$.reading',
    },
    numbers: ['lat', 'value'],
  },
  required: ['name'],
  source: 'Example Widgets',
  attribution: 'Data: example — keyless test.',
  units: { value: 'widgets' },
  honesty: 'Synthetic test spec; never ships.',
  verifiedAt: '2026-10-02',
  verifiedBy: 'unit test',
});

test('numOrNull guards the Number(null)/Number("")===0 trap', () => {
  assert.equal(numOrNull(null), null);
  assert.equal(numOrNull(undefined), null);
  assert.equal(numOrNull(''), null);
  assert.equal(numOrNull('   '), null);
  assert.equal(numOrNull('12.5'), 12.5);
  assert.equal(numOrNull(0), 0);
  assert.equal(numOrNull('abc'), null);
  assert.equal(numOrNull(NaN), null);
});

test('resolvePath handles dots and indices, rejects garbage', () => {
  const root = { a: { b: [{ c: 42 }] }, 'x-y': 7 };
  assert.equal(resolvePath(root, '$'), root);
  assert.equal(resolvePath(root, '$.a.b[0].c'), 42);
  assert.equal(resolvePath(root, '$.x-y'), 7);
  assert.equal(resolvePath(root, '$.a.missing'), undefined);
  assert.equal(resolvePath(root, '$.a.b[5].c'), undefined);
  assert.equal(resolvePath(root, '$.a..b'), undefined);
  assert.equal(resolvePath(root, '$.a.b[*].c'), undefined);
  assert.equal(resolvePath(root, 'a.b'), undefined);
  assert.equal(resolvePath(null, '$.a'), undefined);
});

test('validateSpec accepts a good spec and rejects bad ones', () => {
  assert.equal(validateSpec(goodSpec()), true);
  const bad = (mut) => {
    const s = goodSpec();
    mut(s);
    assert.throws(() => validateSpec(s), /surge_spec_invalid/);
  };
  bad((s) => { s.id = 'Bad_Id'; });
  bad((s) => { s.url = 'http://insecure.example/x'; });
  bad((s) => { delete s.extract; });
  bad((s) => { s.extract.items = 'data.widgets'; });
  bad((s) => { s.extract.map = {}; });
  bad((s) => { s.honesty = ''; });
  bad((s) => { s.verifiedAt = 'yesterday'; });
  bad((s) => { s.title = 'TODO placeholder'; });
});

test('extractItems slices to limit, applyMap resolves + guards numbers', () => {
  const spec = goodSpec();
  const payload = {
    data: {
      widgets: [
        { label: '  Alpha ', codes: ['A1'], loc: { lat: '41.5' }, reading: '' },
        { label: 'Beta', codes: [], loc: {}, reading: '3.25' },
        { label: null, codes: [], loc: {}, reading: 'x' },
      ],
    },
  };
  const items = extractItems(spec, payload);
  assert.equal(items.length, 3);
  const rows = items.map((i) => applyMap(spec, i));
  assert.equal(rows[0].name, 'Alpha'); // trimmed
  assert.equal(rows[0].code, 'A1');
  assert.equal(rows[0].lat, 41.5);
  assert.equal(rows[0].value, null); // '' → null, never 0
  assert.equal(rows[1].value, 3.25);
  const { rows: kept, dropped } = filterRequired(spec, rows);
  assert.equal(kept.length, 2);
  assert.equal(dropped, 1);
  const env = buildPayload(spec, kept, false);
  assert.equal(env.count, 2);
  assert.equal(env.id, 'test-widget');
  assert.ok(env.generatedAt);
});

test('extractItems returns [] when the path misses (never throws)', () => {
  const spec = goodSpec();
  assert.deepEqual(extractItems(spec, {}), []);
  assert.deepEqual(extractItems(spec, { data: { widgets: 'nope' } }), []);
});

test('specProxy builds the plugin interface', () => {
  const plugin = specProxy('test-widget', goodSpec());
  assert.equal(plugin.name, 'test-widget');
  assert.equal(typeof plugin.configureServer, 'function');
  assert.equal(typeof plugin.configurePreviewServer, 'function');
  assert.throws(() => specProxy('nope', {}), /surge_unknown_spec/);
  assert.throws(() => specProxy('test-widget', { id: 'x' }), /surge_spec_invalid/);
});

test('internals exposed for tests', () => {
  assert.equal(typeof _surgeInternals.clearCaches, 'function');
});
