/**
 * Surge-500 spec — AUTO-GENERATED by scripts/surge-generate.mjs.
 * Do not edit by hand; edit ~/workspace/surge-500/specs/gbif-birds.json
 * and re-run the generator. Verified 2026-10-02 (surge-500 batch 7 (gbif worker)).
 */
export const SPEC = {
  "id": "gbif-birds",
  "title": "Bird occurrences worldwide — GBIF (Aves, taxon_key=212)",
  "url": "https://api.gbif.org/v1/occurrence/search?taxon_key=212&limit=20",
  "extract": {
    "items": "$.results",
    "limit": 20,
    "map": {
      "species": "$.species",
      "scientific_name": "$.scientificName",
      "lat": "$.decimalLatitude",
      "lon": "$.decimalLongitude",
      "event_date": "$.eventDate",
      "basis_of_record": "$.basisOfRecord",
      "institution": "$.institutionCode",
      "country": "$.countryCode",
      "taxon_key": "$.taxonKey",
      "iucn": "$.iucnRedListCategory"
    },
    "numbers": [
      "lat",
      "lon"
    ]
  },
  "required": [
    "species"
  ],
  "honesty": "Bird (Aves, GBIF taxon key 212) occurrence records worldwide; coordinates may be absent on some rows. Fixture: 20 rows (108347 bytes), 20/20 rows carry species, 19/20 rows have coordinates; API reports 2362098558 total matching records. Verified 200 OK from this VM.",
  "headers": {},
  "ttlSeconds": 86400,
  "source": "GBIF",
  "attribution": "Data: GBIF.org — keyless, CC BY 4.0.",
  "units": {},
  "verifiedAt": "2026-10-02",
  "verifiedBy": "surge-500 batch 7 (gbif worker)"
};
