/**
 * Surge-500 spec — AUTO-GENERATED by scripts/surge-generate.mjs.
 * Do not edit by hand; edit ~/workspace/surge-500/specs/inat-insects.json
 * and re-run the generator. Verified 2026-10-02 (surge-500 batch 8 (inaturalist worker)).
 */
export const SPEC = {
  id: 'inat-insects',
  title:
    'Recent insect observations worldwide — iNaturalist (Insecta, taxon_id=47158)',
  url: 'https://api.inaturalist.org/v1/observations?per_page=20&order_by=observed_on&order=desc&taxon_id=47158',
  extract: {
    items: '$.results',
    limit: 20,
    map: {
      observation_id: '$.id',
      species_guess: '$.species_guess',
      scientific_name: '$.taxon.name',
      common_name: '$.taxon.preferred_common_name',
      iconic_taxon: '$.taxon.iconic_taxon_name',
      observed_on: '$.observed_on',
      location: '$.location',
      quality_grade: '$.quality_grade',
      observer: '$.user.login',
      observation_url: '$.uri',
    },
    numbers: [],
  },
  required: ['observation_id'],
  honesty:
    'Recent insect observations worldwide; API reports 98525484 total matching records. Fixture: 20 rows (513571 bytes), 20/20 rows carry observation_id, 20/20 carry scientific_name, 13/20 carry species_guess, 19/20 carry coordinates, 20/20 carry observed_on, 20/20 carry observer. Coordinates absent on some rows. Verified 200 OK from this VM.',
  headers: {},
  ttlSeconds: 86400,
  source: 'iNaturalist',
  attribution: 'Data: iNaturalist.org — keyless, CC0/CC-BY.',
  units: {},
  verifiedAt: '2026-10-02',
  verifiedBy: 'surge-500 batch 8 (inaturalist worker)',
};
