/**
 * Surge-500 spec — AUTO-GENERATED by scripts/surge-generate.mjs.
 * Do not edit by hand; edit ~/workspace/surge-500/specs/socrata-la-311.json
 * and re-run the generator. Verified 2026-10-02 (surge-500 batch 6 (socrata2 worker)).
 */
export const SPEC = {
  "id": "socrata-la-311",
  "title": "Los Angeles (data.lacity.org) — MyLA311 service requests (2025)",
  "url": "https://data.lacity.org/resource/h73f-gn57.json?%24limit=50&%24order=createddate%20DESC",
  "headers": {},
  "ttlSeconds": 3600,
  "extract": {
    "items": "$",
    "limit": 50,
    "map": {
      "key": "$.srnumber",
      "type": "$.requesttype",
      "status": "$.status",
      "created": "$.createddate",
      "updated": "$.updateddate",
      "source": "$.requestsource",
      "action": "$.actiontaken"
    },
    "numbers": []
  },
  "required": [
    "key",
    "type"
  ],
  "source": "City of Los Angeles — data.lacity.org (Socrata)",
  "attribution": "Data: City of Los Angeles — data.lacity.org (Socrata) — keyless Socrata API.",
  "units": {},
  "honesty": "Annual MyLA311 slice for calendar 2025 (a fresh-2026 slice does not exist on this portal); all 50 fixture rows dated 2025-10/11. For a rolling feed see the 2026 slice if published. createddate ISO-8601. Verified 50 rows in fixture (42084 bytes).",
  "verifiedAt": "2026-10-02",
  "verifiedBy": "surge-500 batch 6 (socrata2 worker)"
};
