/**
 * Surge-500 spec — AUTO-GENERATED by scripts/surge-generate.mjs.
 * Do not edit by hand; edit ~/workspace/surge-500/specs/wb-gdp-usa.json
 * and re-run the generator. Verified 2026-10-02 (surge-500 batch-4 diversity worker).
 */
export const SPEC = {
  attribution: 'Data: World Bank (CC BY-4.0) — keyless.',
  extract: {
    items: '$[1]',
    limit: 50,
    map: {
      country: '$.country.value',
      gdpUSD: '$.value',
      indicator: '$.indicator.value',
      year: '$.date',
    },
    numbers: ['gdpUSD'],
  },
  fieldMap: {
    country: 'country name',
    gdpUSD: 'GDP in current US dollars',
    indicator: 'indicator label',
    year: 'calendar year',
  },
  headers: {
    'User-Agent':
      'satwq-reality-os/1.0 (gods-eye-view; surge-500 layer; keyless)',
  },
  honestLabels: {
    coverage: 'USA only, 2000–2024, one observation per year.',
    freshness:
      'Annual series; latest observation per World Bank lastupdated 2026-07-13.',
    model: 'None — official World Bank WDI series.',
  },
  honesty:
    'Annual World Bank WDI series NY.GDP.MKTP.CD for the United States, current US$. Updated yearly — not real-time.',
  id: 'wb-gdp-usa',
  required: ['year', 'gdpUSD'],
  source: 'World Bank World Development Indicators',
  title: 'World Bank — USA GDP, current US$ (annual)',
  ttlSeconds: 86400,
  units: {
    gdpUSD: 'USD',
  },
  url: 'https://api.worldbank.org/v2/country/USA/indicator/NY.GDP.MKTP.CD?format=json&per_page=60&date=2000:2024',
  verifiedAt: '2026-10-02',
  verifiedBy: 'surge-500 batch-4 diversity worker',
};
